-- 0028 : placeholders SVT lycee (Secondes/Premieres/Terminales A,C,D).
-- Meme structure que 0019/0020, idempotent. Matiere 'svt' existante.

insert into chapters (slug, title, class_slug, subject_key, sort_order) values
('seconde-svt-1', 'Gestion durable de l''environnement', 'seconde', 'svt', 1),
('seconde-svt-2', 'Nutrition des plantes vertes', 'seconde', 'svt', 2),
('seconde-c-svt-1', 'Gestion durable de l''environnement', 'seconde-c', 'svt', 1),
('seconde-c-svt-2', 'Nutrition des plantes vertes', 'seconde-c', 'svt', 2),
('seconde-c-svt-3', 'Sols et géologie historique', 'seconde-c', 'svt', 3),
('premiere-svt-1', 'La matière des êtres vivants', 'premiere', 'svt', 1),
('premiere-svt-2', 'La cellule', 'premiere', 'svt', 2),
('premiere-svt-3', 'La nutrition des animaux et de l''homme', 'premiere', 'svt', 3),
('premiere-c-svt-1', 'La matière des êtres vivants', 'premiere-c', 'svt', 1),
('premiere-c-svt-2', 'La cellule', 'premiere-c', 'svt', 2),
('premiere-c-svt-3', 'La nutrition des animaux et de l''homme', 'premiere-c', 'svt', 3),
('premiere-d-svt-1', 'La géologie', 'premiere-d', 'svt', 1),
('premiere-d-svt-2', 'La matière des êtres vivants', 'premiere-d', 'svt', 2),
('premiere-d-svt-3', 'La cellule', 'premiere-d', 'svt', 3),
('premiere-d-svt-4', 'La nutrition des animaux et de l''homme', 'premiere-d', 'svt', 4),
('terminale-svt-1', 'Génétique', 'terminale', 'svt', 1),
('terminale-svt-2', 'Reproduction sexuée chez les êtres vivants', 'terminale', 'svt', 2),
('terminale-svt-3', 'Homéostasie', 'terminale', 'svt', 3),
('terminale-c-svt-1', 'Génétique', 'terminale-c', 'svt', 1),
('terminale-c-svt-2', 'Reproduction sexuée chez les êtres vivants', 'terminale-c', 'svt', 2),
('terminale-c-svt-3', 'Relations de l''homme avec son milieu', 'terminale-c', 'svt', 3),
('terminale-c-svt-4', 'Homéostasie', 'terminale-c', 'svt', 4),
('terminale-d-svt-1', 'Génétique', 'terminale-d', 'svt', 1),
('terminale-d-svt-2', 'Reproduction sexuée chez les êtres vivants', 'terminale-d', 'svt', 2),
('terminale-d-svt-3', 'Relations de l''Homme avec son milieu', 'terminale-d', 'svt', 3),
('terminale-d-svt-4', 'Homéostasie', 'terminale-d', 'svt', 4)
on conflict (slug) do nothing;

insert into subchapters (slug, title, chapter_id, sort_order)
select v.slug, v.title, c.id, v.sort_order from (values
('seconde-svt-1-s1', 'Leçon 1 : Les êtres vivants dans leur milieu', 'seconde-svt-1', 1),
('seconde-svt-1-s2', 'Leçon 2 : Les équilibres naturels', 'seconde-svt-1', 2),
('seconde-svt-2-s1', 'Leçon 3 : La nutrition minérale des plantes vertes', 'seconde-svt-2', 1),
('seconde-svt-2-s2', 'Leçon 4 : La nutrition carbonée des plantes vertes (la photosynthèse)', 'seconde-svt-2', 2),
('seconde-c-svt-1-s1', 'Leçon 1 : Les êtres vivants dans leur milieu', 'seconde-c-svt-1', 1),
('seconde-c-svt-1-s2', 'Leçon 2 : Les équilibres naturels', 'seconde-c-svt-1', 2),
('seconde-c-svt-2-s1', 'Leçon 3 : La nutrition minérale des plantes vertes', 'seconde-c-svt-2', 1),
('seconde-c-svt-2-s2', 'Leçon 4 : La nutrition carbonée des plantes vertes (la photosynthèse)', 'seconde-c-svt-2', 2),
('seconde-c-svt-3-s1', 'Leçon 5 : L''origine et l''évolution des sols', 'seconde-c-svt-3', 1),
('seconde-c-svt-3-s2', 'Leçon 6 : La géologie historique (stratigraphie et paléontologie)', 'seconde-c-svt-3', 2),
('premiere-svt-1-s1', 'Leçon 1 : Les constituants de la matière des êtres vivants', 'premiere-svt-1', 1),
('premiere-svt-2-s1', 'Leçon 2 : L''organisation de la cellule', 'premiere-svt-2', 1),
('premiere-svt-2-s2', 'Leçon 3 : Les échanges cellulaires', 'premiere-svt-2', 2),
('premiere-svt-2-s3', 'Leçon 4 : Les divisions cellulaires', 'premiere-svt-2', 3),
('premiere-svt-3-s1', 'Leçon 5 : La respiration', 'premiere-svt-3', 1),
('premiere-c-svt-1-s1', 'Leçon 1 : Les constituants de la matière des êtres vivants', 'premiere-c-svt-1', 1),
('premiere-c-svt-2-s1', 'Leçon 2 : L''organisation de la cellule', 'premiere-c-svt-2', 1),
('premiere-c-svt-2-s2', 'Leçon 3 : Les échanges cellulaires', 'premiere-c-svt-2', 2),
('premiere-c-svt-2-s3', 'Leçon 4 : Les divisions cellulaires', 'premiere-c-svt-2', 3),
('premiere-c-svt-3-s1', 'Leçon 5 : La respiration', 'premiere-c-svt-3', 1),
('premiere-c-svt-3-s2', 'Leçon 6 : Les fermentations', 'premiere-c-svt-3', 2),
('premiere-c-svt-3-s3', 'Leçon 7 : Le cycle de la matière', 'premiere-c-svt-3', 3),
('premiere-d-svt-1-s1', 'Leçon 1 : La tectonique globale', 'premiere-d-svt-1', 1),
('premiere-d-svt-1-s2', 'Leçon 2 : Les grandes formations géologiques du Togo', 'premiere-d-svt-1', 2),
('premiere-d-svt-2-s1', 'Leçon 3 : Les constituants de la matière des êtres vivants', 'premiere-d-svt-2', 1),
('premiere-d-svt-3-s1', 'Leçon 4 : L''organisation de la cellule', 'premiere-d-svt-3', 1),
('premiere-d-svt-3-s2', 'Leçon 5 : Les échanges cellulaires', 'premiere-d-svt-3', 2),
('premiere-d-svt-3-s3', 'Leçon 6 : Les divisions cellulaires', 'premiere-d-svt-3', 3),
('premiere-d-svt-4-s1', 'Leçon 7 : La respiration', 'premiere-d-svt-4', 1),
('premiere-d-svt-4-s2', 'Leçon 8 : Les fermentations', 'premiere-d-svt-4', 2),
('premiere-d-svt-4-s3', 'Leçon 9 : Le cycle de la matière', 'premiere-d-svt-4', 3),
('terminale-svt-1-s1', 'Leçon 1 : Le matériel génétique et la transmission des caractères héréditaires', 'terminale-svt-1', 1),
('terminale-svt-1-s2', 'Leçon 2 : L''hérédité humaine', 'terminale-svt-1', 2),
('terminale-svt-2-s1', 'Leçon 3 : La gamétogenèse et la fécondation', 'terminale-svt-2', 1),
('terminale-svt-3-s1', 'Leçon 4 : L''immunologie', 'terminale-svt-3', 1),
('terminale-svt-3-s2', 'Leçon 5 : L''activité cardiaque et la pression artérielle', 'terminale-svt-3', 2),
('terminale-c-svt-1-s1', 'Leçon 1 : Le matériel génétique et la transmission des caractères héréditaires', 'terminale-c-svt-1', 1),
('terminale-c-svt-1-s2', 'Leçon 2 : L''hérédité humaine', 'terminale-c-svt-1', 2),
('terminale-c-svt-2-s1', 'Leçon 3 : La gamétogenèse et la fécondation', 'terminale-c-svt-2', 1),
('terminale-c-svt-3-s1', 'Leçon 4 : Le tissu nerveux et ses propriétés', 'terminale-c-svt-3', 1),
('terminale-c-svt-4-s1', 'Leçon 5 : L''immunologie', 'terminale-c-svt-4', 1),
('terminale-c-svt-4-s2', 'Leçon 6 : L''activité cardiaque et la pression artérielle', 'terminale-c-svt-4', 2),
('terminale-d-svt-1-s1', 'Leçon 1 : Le matériel génétique et la transmission des caractères héréditaires', 'terminale-d-svt-1', 1),
('terminale-d-svt-1-s2', 'Leçon 2 : L''hérédité humaine', 'terminale-d-svt-1', 2),
('terminale-d-svt-2-s1', 'Leçon 3 : La gamétogenèse et la régulation des cycles sexuels chez l''Homme', 'terminale-d-svt-2', 1),
('terminale-d-svt-2-s2', 'Leçon 4 : La fécondation et les premières étapes de la vie chez l''Homme', 'terminale-d-svt-2', 2),
('terminale-d-svt-2-s3', 'Leçon 5 : La reproduction chez les Spermaphytes', 'terminale-d-svt-2', 3),
('terminale-d-svt-3-s1', 'Leçon 6 : Le tissu nerveux et ses propriétés', 'terminale-d-svt-3', 1),
('terminale-d-svt-3-s2', 'Leçon 7 : La physiologie du muscle strié squelettique', 'terminale-d-svt-3', 2),
('terminale-d-svt-4-s1', 'Leçon 8 : L''immunologie', 'terminale-d-svt-4', 1),
('terminale-d-svt-4-s2', 'Leçon 9 : La régulation du milieu intérieur', 'terminale-d-svt-4', 2),
('terminale-d-svt-4-s3', 'Leçon 10 : L''activité cardiaque et la pression artérielle', 'terminale-d-svt-4', 3)
) as v(slug,title,chapter_slug,sort_order)
join chapters c on c.slug=v.chapter_slug
on conflict (slug) do nothing;

insert into lessons (slug, title, summary, chapter_id, subchapter_id, sort_order, status, is_free_preview)
select v.slug, v.title, v.summary, c.id, sc.id, v.sort_order, 'draft', false from (values
('seconde-svt-1-s1-l1', 'Le matériel de la sortie écologique', 'Utiliser sur le terrain le matériel adapté (loupe, flacon, pince, boussole, filet) pour étudier les êtres vivants d''un milieu.', 'seconde-svt-1', 'seconde-svt-1-s1', 1),
('seconde-svt-1-s1-l2', 'Identifier les êtres vivants dans leur milieu', 'Repérer animaux et végétaux dans leurs milieux habituels (sol, sous-sol, eau, air) : insectes, vers, graminées, plantes aquatiques.', 'seconde-svt-1', 'seconde-svt-1-s1', 2),
('seconde-svt-1-s1-l3', 'Les notions clés de l''écologie', 'Définir écologie, biotope, biocénose, écosystème, biomasse et environnement à partir des relations entre êtres vivants.', 'seconde-svt-1', 'seconde-svt-1-s1', 3),
('seconde-svt-1-s1-l4', 'Les zones écofloristiques du Togo', 'Localiser les principales zones abritant les écosystèmes au Togo : mangrove, savane, forêt et milieux aquatiques.', 'seconde-svt-1', 'seconde-svt-1-s1', 4),
('seconde-svt-1-s1-l5', 'Relations entre êtres vivants et effets de nombre', 'Distinguer relations intraspécifiques et interspécifiques, puis caractériser l''effet de groupe et l''effet de masse.', 'seconde-svt-1', 'seconde-svt-1-s1', 5),
('seconde-svt-1-s1-l6', 'Chaînes alimentaires et interdépendance', 'Construire chaîne et réseau trophiques, expliquer transferts d''énergie et l''interdépendance en lutte biologique et fertilisation des sols.', 'seconde-svt-1', 'seconde-svt-1-s1', 6),
('seconde-svt-1-s2-l1', 'Effet de serre et réchauffement de la planète', 'Expliquer le mécanisme de l''effet de serre et les activités humaines à l''origine du réchauffement de la planète.', 'seconde-svt-1', 'seconde-svt-1-s2', 7),
('seconde-svt-1-s2-l2', 'Les grands problèmes environnementaux', 'Identifier pollution des eaux, érosion côtière, déforestation, dégradation des sols, pesticides, pêche anarchique, braconnage et feux de brousse.', 'seconde-svt-1', 'seconde-svt-1-s2', 8),
('seconde-svt-1-s2-l3', 'Conséquences sur le développement durable', 'Déduire les conséquences des changements climatiques, de la perte de biodiversité et des pollutions sur le développement durable.', 'seconde-svt-1', 'seconde-svt-1-s2', 9),
('seconde-svt-1-s2-l4', 'Les mesures de protection de l''environnement', 'Proposer reboisement, pare-feux, agroforesterie, recyclage et gestion rationnelle des ressources naturelles.', 'seconde-svt-1', 'seconde-svt-1-s2', 10),
('seconde-svt-1-s2-l5', 'Produire des affiches de sensibilisation', 'Réaliser des affiches pour sensibiliser ses pairs au maintien de l''équilibre de la nature et aux comportements responsables.', 'seconde-svt-1', 'seconde-svt-1-s2', 11),
('seconde-svt-2-s1-l1', 'Développement d''une plante verte', 'Décrire les étapes de la germination (hétérotrophie) puis de la croissance (autotrophie) d''une plante verte.', 'seconde-svt-2', 'seconde-svt-2-s1', 1),
('seconde-svt-2-s1-l2', 'Le rôle des sels minéraux', 'Déterminer le rôle des sels minéraux azote, phosphore et potassium (N, P, K) et la notion de concentration optimale.', 'seconde-svt-2', 'seconde-svt-2-s1', 2),
('seconde-svt-2-s1-l3', 'Applications de la nutrition minérale', 'Déduire les usages pratiques : préparation d''engrais, culture sous serre, culture sans sol et aquaculture.', 'seconde-svt-2', 'seconde-svt-2-s1', 3),
('seconde-svt-2-s1-l4', 'Réaliser des cultures de légumes', 'Aménager cultures et jardins potagers (tomates, haricot vert, fleurs) à l''école ou à la maison.', 'seconde-svt-2', 'seconde-svt-2-s1', 4),
('seconde-svt-2-s2-l1', 'Les échanges gazeux chlorophylliens', 'Mettre en évidence les échanges gazeux chlorophylliens d''une plante verte à la lumière et à l''obscurité.', 'seconde-svt-2', 'seconde-svt-2-s2', 5),
('seconde-svt-2-s2-l2', 'Intensité et quotient d''assimilation', 'Calculer l''intensité d''assimilation chlorophyllienne et le quotient d''assimilation chlorophyllien.', 'seconde-svt-2', 'seconde-svt-2-s2', 6),
('seconde-svt-2-s2-l3', 'Mettre en évidence l''amidon', 'Réaliser l''expérience de mise en évidence de l''amidon dans une feuille pour révéler un produit de la photosynthèse.', 'seconde-svt-2', 'seconde-svt-2-s2', 7),
('seconde-svt-2-s2-l4', 'Chloroplaste et facteurs de la photosynthèse', 'Schématiser l''ultrastructure du chloroplaste et conclure sur les facteurs indispensables : chlorophylle, lumière, CO2, température.', 'seconde-svt-2', 'seconde-svt-2-s2', 8),
('seconde-svt-2-s2-l5', 'Le mécanisme de la photosynthèse', 'Expliquer la phase claire (photolyse de l''eau), la phase sombre (réduction du CO2) et écrire le bilan des réactions.', 'seconde-svt-2', 'seconde-svt-2-s2', 9),
('seconde-svt-2-s2-l6', 'Importance de la photosynthèse', 'Illustrer son rôle : reboisement, production de dioxygène, production alimentaire, pharmaceutique et de biopesticides.', 'seconde-svt-2', 'seconde-svt-2-s2', 10),
('seconde-c-svt-1-s1-l1', 'Le matériel de la sortie écologique', 'Utiliser sur le terrain le matériel nécessaire à l''étude des êtres vivants au cours d''une sortie écologique.', 'seconde-c-svt-1', 'seconde-c-svt-1-s1', 1),
('seconde-c-svt-1-s1-l2', 'Identifier les êtres vivants dans leurs milieux', 'Reconnaître animaux et végétaux dans le sol, le sous-sol, l''eau et l''air, avec des exemples togolais.', 'seconde-c-svt-1', 'seconde-c-svt-1-s1', 2),
('seconde-c-svt-1-s1-l3', 'Notions fondamentales d''écologie', 'Définir écologie, biotope, biocénose, écosystème, biomasse et environnement à partir des observations.', 'seconde-c-svt-1', 'seconde-c-svt-1-s1', 3),
('seconde-c-svt-1-s1-l4', 'Les zones écofloristiques du Togo', 'Localiser les principales zones abritant les écosystèmes au Togo : mangrove, savane, forêt, milieux aquatiques.', 'seconde-c-svt-1', 'seconde-c-svt-1-s1', 4),
('seconde-c-svt-1-s1-l5', 'Chaînes alimentaires et réseaux trophiques', 'Construire une chaîne alimentaire, repérer maillons et réseaux, expliquer les transferts de matière et d''énergie.', 'seconde-c-svt-1', 'seconde-c-svt-1-s1', 5),
('seconde-c-svt-1-s1-l6', 'Relations entre êtres vivants et interdépendance', 'Comparer relations intraspécifiques et interspécifiques, effet de groupe et effet de masse, et l''interdépendance.', 'seconde-c-svt-1', 'seconde-c-svt-1-s1', 6),
('seconde-c-svt-1-s2-l1', 'Les grands problèmes environnementaux', 'Identifier pollutions, déforestation, érosion côtière, perte de biodiversité, surpâturage, feux de brousse et braconnage.', 'seconde-c-svt-1', 'seconde-c-svt-1-s2', 7),
('seconde-c-svt-1-s2-l2', 'Effet de serre et réchauffement de la planète', 'Expliquer le mécanisme de l''effet de serre, les gaz responsables et la destruction de la couche d''ozone.', 'seconde-c-svt-1', 'seconde-c-svt-1-s2', 8),
('seconde-c-svt-1-s2-l3', 'Conséquences sur les écosystèmes', 'Déduire les conséquences des changements climatiques, des pollutions et de la disparition des espèces.', 'seconde-c-svt-1', 'seconde-c-svt-1-s2', 9),
('seconde-c-svt-1-s2-l4', 'Mesures de protection de l''environnement', 'Proposer reboisement, pare-feux, agroforesterie, recyclage et gestion durable des ressources naturelles.', 'seconde-c-svt-1', 'seconde-c-svt-1-s2', 10),
('seconde-c-svt-1-s2-l5', 'Produire des affiches de sensibilisation', 'Réaliser des affiches sensibilisant ses pairs au maintien de l''équilibre de la nature.', 'seconde-c-svt-1', 'seconde-c-svt-1-s2', 11),
('seconde-c-svt-2-s1-l1', 'Germination et croissance d''une plante verte', 'Décrire les étapes de développement : germination hétérotrophe puis croissance autotrophe.', 'seconde-c-svt-2', 'seconde-c-svt-2-s1', 1),
('seconde-c-svt-2-s1-l2', 'Rôle des sels minéraux N, P, K', 'Déterminer le rôle de chaque sel minéral et la notion de concentration optimale pour la croissance.', 'seconde-c-svt-2', 'seconde-c-svt-2-s1', 2),
('seconde-c-svt-2-s1-l3', 'Applications de la nutrition minérale', 'Déduire les applications : préparation d''engrais, culture sous serre, culture sans sol et aquaculture.', 'seconde-c-svt-2', 'seconde-c-svt-2-s1', 3),
('seconde-c-svt-2-s1-l4', 'Réaliser des cultures de légumes', 'Réaliser des cultures de tomates, haricot vert et fleurs dans le cadre d''espaces verts.', 'seconde-c-svt-2', 'seconde-c-svt-2-s1', 4),
('seconde-c-svt-2-s2-l1', 'Les échanges gazeux chlorophylliens', 'Mettre en évidence et analyser les échanges gazeux chlorophylliens à la lumière et à l''obscurité.', 'seconde-c-svt-2', 'seconde-c-svt-2-s2', 5),
('seconde-c-svt-2-s2-l2', 'Intensité et quotient d''assimilation chlorophylliens', 'Calculer l''intensité d''assimilation chlorophyllienne et le quotient d''assimilation chlorophyllien.', 'seconde-c-svt-2', 'seconde-c-svt-2-s2', 6),
('seconde-c-svt-2-s2-l3', 'Mise en évidence de l''amidon et facteurs', 'Révéler l''amidon dans une feuille et conclure sur chlorophylle, lumière, dioxyde de carbone et température.', 'seconde-c-svt-2', 'seconde-c-svt-2-s2', 7),
('seconde-c-svt-2-s2-l4', 'Chloroplaste et pigments chlorophylliens', 'Schématiser l''ultrastructure du chloroplaste et séparer les pigments foliaires par chromatographie.', 'seconde-c-svt-2', 'seconde-c-svt-2-s2', 8),
('seconde-c-svt-2-s2-l5', 'Mécanisme de la photosynthèse', 'Expliquer la phase claire, la phase sombre et écrire le bilan des réactions de la photosynthèse.', 'seconde-c-svt-2', 'seconde-c-svt-2-s2', 9),
('seconde-c-svt-2-s2-l6', 'Importance de la photosynthèse', 'Illustrer son rôle : reboisement, production alimentaire, pharmaceutique et biopesticides.', 'seconde-c-svt-2', 'seconde-c-svt-2-s2', 10),
('seconde-c-svt-3-s1-l1', 'Matériel et étude d''un sol sur le terrain', 'Utiliser les outils appropriés pour l''étude d''un sol au cours d''une sortie et prélever des échantillons.', 'seconde-c-svt-3', 'seconde-c-svt-3-s1', 1),
('seconde-c-svt-3-s1-l2', 'Types de sols et leurs caractéristiques', 'Identifier sableux, argileux, ferrugineux, ferralitiques et leurs caractéristiques : perméabilité, texture, pH.', 'seconde-c-svt-3', 'seconde-c-svt-3-s1', 2),
('seconde-c-svt-3-s1-l3', 'Répartition des sols au Togo', 'Identifier les différents types de sols du Togo à l''aide d''une carte simplifiée de leur répartition.', 'seconde-c-svt-3', 'seconde-c-svt-3-s1', 3),
('seconde-c-svt-3-s1-l4', 'Formation d''un sol', 'Expliquer la formation : altération de la roche mère et accumulation des débris végétaux et minéraux.', 'seconde-c-svt-3', 'seconde-c-svt-3-s1', 4),
('seconde-c-svt-3-s1-l5', 'Dégradation des sols', 'Décrire la dégradation sous les facteurs naturels et anthropiques : érosion, lessivage, acidification.', 'seconde-c-svt-3', 'seconde-c-svt-3-s1', 5),
('seconde-c-svt-3-s1-l6', 'Protection et reconstitution des sols', 'Décrire les techniques : reboisement, culture en terrasse et compostage.', 'seconde-c-svt-3', 'seconde-c-svt-3-s1', 6),
('seconde-c-svt-3-s2-l1', 'Les principes de la stratigraphie', 'Enoncer les principes fondamentaux de la stratigraphie et leurs limites d''application.', 'seconde-c-svt-3', 'seconde-c-svt-3-s2', 7),
('seconde-c-svt-3-s2-l2', 'Concordance et discordances stratigraphiques', 'Expliquer la concordance et les discordances fondamentale, angulaire et de ravinement.', 'seconde-c-svt-3', 'seconde-c-svt-3-s2', 8),
('seconde-c-svt-3-s2-l3', 'Régression et transgression marines', 'Décrire les phénomènes de régression et de transgression marines dans les formations géologiques.', 'seconde-c-svt-3', 'seconde-c-svt-3-s2', 9),
('seconde-c-svt-3-s2-l4', 'La géochronologie relative et absolue', 'Etablir la géochronologie des formations, du principe de datation absolue au carbone 14.', 'seconde-c-svt-3', 'seconde-c-svt-3-s2', 10),
('seconde-c-svt-3-s2-l5', 'Fossiles et processus de fossilisation', 'Décrire les fossiles togolais, les conditions et les différentes formes de fossilisation.', 'seconde-c-svt-3', 'seconde-c-svt-3-s2', 11),
('seconde-c-svt-3-s2-l6', 'L''intérêt de l''étude des fossiles', 'Déduire l''intérêt géologique (fossiles stratigraphiques et de faciès) et biologique des fossiles.', 'seconde-c-svt-3', 'seconde-c-svt-3-s2', 12),
('premiere-svt-1-s1-l1', 'Les constituants minéraux et organiques', 'Les constituants minéraux (eau, sels minéraux) et organiques (glucides, protides, lipides) de la matière vivante.', 'premiere-svt-1', 'premiere-svt-1-s1', 1),
('premiere-svt-1-s1-l2', 'Les rôles de l''eau', 'Rôles de l''eau : solvant, plastique, thermorégulateur, transport des sels et nutriments, osmorégulateur.', 'premiere-svt-1', 'premiere-svt-1-s1', 2),
('premiere-svt-1-s1-l3', 'Les propriétés des glucides', 'Glucides solubles (glucose) ou insolubles (amidon), fermentescibles, composés d''oses ou sucres simples.', 'premiere-svt-1', 'premiere-svt-1-s1', 3),
('premiere-svt-1-s1-l4', 'Les propriétés des protides', 'Protides coagulables par l''acide ou la chaleur, insolubles dans l''eau, composés d''acides aminés.', 'premiere-svt-1', 'premiere-svt-1-s1', 4),
('premiere-svt-1-s1-l5', 'Les lipides et la fabrication du savon', 'Lipides insolubles dans l''eau, solubles dans les solvants organiques, tache translucide ; application au savon.', 'premiere-svt-1', 'premiere-svt-1-s1', 5),
('premiere-svt-1-s1-l6', 'Les types de solutions', 'Réaliser et distinguer solution vraie, solution colloïdale, suspension et émulsion à partir des constituants.', 'premiere-svt-1', 'premiere-svt-1-s1', 6),
('premiere-svt-2-s1-l1', 'La structure de la cellule au microscope', 'Structure de la cellule au microscope optique et électronique ; cellules eucaryotes et procaryotes.', 'premiere-svt-2', 'premiere-svt-2-s1', 1),
('premiere-svt-2-s1-l2', 'Les parties et organites de la cellule', 'Membrane, paroi, vacuoles, cytoplasme, réticulum, Golgi, mitochondries, chloroplastes, noyau, centrosome.', 'premiere-svt-2', 'premiere-svt-2-s1', 2),
('premiere-svt-2-s1-l3', 'Cellule animale et cellule végétale', 'Points communs et différences entre cellule animale et végétale : plastes, centrosome, vacuoles, paroi.', 'premiere-svt-2', 'premiere-svt-2-s1', 3),
('premiere-svt-2-s1-l4', 'Le rôle des organites cellulaires', 'Rôle des différentes parties et organites de la cellule dans son fonctionnement.', 'premiere-svt-2', 'premiere-svt-2-s1', 4),
('premiere-svt-2-s2-l1', 'Des exemples d''échanges cellulaires', 'Absorption racinaire, échanges gazeux chlorophylliens et respiratoires, absorption intestinale.', 'premiere-svt-2', 'premiere-svt-2-s2', 5),
('premiere-svt-2-s2-l2', 'Cellules en milieux isotonique, hypotonique et hypertonique', 'État des globules rouges et des cellules d''oignon selon la concentration : normal, turgescent, plasmolysé.', 'premiere-svt-2', 'premiere-svt-2-s2', 6),
('premiere-svt-2-s2-l3', 'L''osmose et l''expérience de Dutrochet', 'Principe de l''osmose et mécanisme d''échange d''eau illustré par l''expérience de Dutrochet.', 'premiere-svt-2', 'premiere-svt-2-s2', 7),
('premiere-svt-2-s2-l4', 'Le transport passif et le transport actif', 'Transport passif (diffusion libre et facilitée) sans énergie et transport actif contre le gradient avec énergie.', 'premiere-svt-2', 'premiere-svt-2-s2', 8),
('premiere-svt-2-s2-l5', 'Importance et applications des échanges cellulaires', 'Échanges de matière et d''énergie ; applications en médecine (hémodialyse, sérums) et en agronomie.', 'premiere-svt-2', 'premiere-svt-2-s2', 9),
('premiere-svt-2-s3-l1', 'Les chromosomes et le caryotype', 'Définitions de la mitose et de la méiose, localisation et structure des chromosomes, caryotype.', 'premiere-svt-2', 'premiere-svt-2-s3', 10),
('premiere-svt-2-s3-l2', 'Les étapes de la mitose', 'Les quatre étapes de la mitose : prophase, métaphase, anaphase, télophase.', 'premiere-svt-2', 'premiere-svt-2-s3', 11),
('premiere-svt-2-s3-l3', 'Les étapes de la méiose', 'Division réductionnelle et division équationnelle, chacune en prophase, métaphase, anaphase, télophase.', 'premiere-svt-2', 'premiere-svt-2-s3', 12),
('premiere-svt-2-s3-l4', 'Le cycle cellulaire', 'Interphase (phases G1, S, G2) et mitose ; description de chaque phase du cycle cellulaire.', 'premiere-svt-2', 'premiere-svt-2-s3', 13),
('premiere-svt-2-s3-l5', 'Comparaison et importance de la mitose et de la méiose', 'Points communs et différences ; importance : reproduction conforme et non conforme, brassage génétique.', 'premiere-svt-2', 'premiere-svt-2-s3', 14),
('premiere-svt-2-s3-l6', 'Facteurs de risque des divisions anarchiques et anomalies chromosomiques', 'Facteurs modifiables et non modifiables des cancers ; rayonnements et produits chimiques pour les anomalies.', 'premiere-svt-2', 'premiere-svt-2-s3', 15),
('premiere-svt-3-s1-l1', 'La mise en évidence des échanges gazeux respiratoires', 'Expériences montrant l''absorption du dioxygène et le dégagement du dioxyde de carbone.', 'premiere-svt-3', 'premiere-svt-3-s1', 1),
('premiere-svt-3-s1-l2', 'Le transport sanguin des gaz respiratoires', 'Structure de l''hémoglobine et formes de transport du dioxygène et du dioxyde de carbone.', 'premiere-svt-3', 'premiere-svt-3-s1', 2),
('premiere-svt-3-s1-l3', 'La respiration cellulaire et l''oxydation du glucose', 'Siège de la respiration cellulaire et équation bilan de l''oxydation cellulaire du glucose.', 'premiere-svt-3', 'premiere-svt-3-s1', 3),
('premiere-svt-3-s1-l4', 'Les maladies respiratoires et leurs facteurs de risque', 'Maladies respiratoires fréquentes et facteurs de risque : tabac, pollution, infections, allergènes.', 'premiere-svt-3', 'premiere-svt-3-s1', 4),
('premiere-c-svt-1-s1-l1', 'Les constituants minéraux et organiques de la matière vivante', 'Eau et sels minéraux comme constituants minéraux ; glucides, protides et lipides comme constituants organiques.', 'premiere-c-svt-1', 'premiere-c-svt-1-s1', 1),
('premiere-c-svt-1-s1-l2', 'La teneur en eau et les rôles de l''eau', 'Calcul de la teneur en eau par rapport à la masse fraîche et rôles de l''eau : solvant, plastique, thermorégulateur, transport, osmorégulateur.', 'premiere-c-svt-1', 'premiere-c-svt-1-s1', 2),
('premiere-c-svt-1-s1-l3', 'Propriétés et composition des glucides, protides et lipides', 'Solubilité, coagulation et composition (oses, acides aminés, acides gras et alcool) des trois grandes substances organiques.', 'premiere-c-svt-1', 'premiere-c-svt-1-s1', 3),
('premiere-c-svt-1-s1-l4', 'La fabrication du savon à partir des lipides', 'Application des lipides : expérience de saponification et équation-bilan de la formation des savons.', 'premiere-c-svt-1', 'premiere-c-svt-1-s1', 4),
('premiere-c-svt-1-s1-l5', 'Les différents types de solutions', 'Réalisation et distinction de la solution vraie, de la solution colloïdale, de la suspension et de l''émulsion.', 'premiere-c-svt-1', 'premiere-c-svt-1-s1', 5),
('premiere-c-svt-2-s1-l1', 'La structure générale de la cellule au microscope', 'Structure au microscope optique et ultrastructure au microscope électronique ; cellules eucaryotes et procaryotes.', 'premiere-c-svt-2', 'premiere-c-svt-2-s1', 1),
('premiere-c-svt-2-s1-l2', 'Les différentes parties et organites de la cellule', 'Membrane, paroi, vacuoles, cytoplasme, réticulum endoplasmique, Golgi, mitochondries, chloroplastes, noyau et centrosome.', 'premiere-c-svt-2', 'premiere-c-svt-2-s1', 2),
('premiere-c-svt-2-s1-l3', 'Comparaison entre cellule animale et cellule végétale', 'Points communs (noyau, mitochondries) et différences (plastes, centrosome, vacuoles, paroi pecto-cellulosique).', 'premiere-c-svt-2', 'premiere-c-svt-2-s1', 3),
('premiere-c-svt-2-s1-l4', 'Le rôle des différentes parties et organites de la cellule', 'Fonctions de la membrane, de la paroi, des vacuoles, du cytoplasme, des organites et du noyau, sans étude de l''ADN.', 'premiere-c-svt-2', 'premiere-c-svt-2-s1', 4),
('premiere-c-svt-2-s2-l1', 'Exemples d''échanges cellulaires', 'Absorption racinaire d''eau et de sels, échanges gazeux chlorophylliens et respiratoires, absorption intestinale.', 'premiere-c-svt-2', 'premiere-c-svt-2-s2', 5),
('premiere-c-svt-2-s2-l2', 'État des cellules animales en milieux de concentrations différentes', 'Globules rouges en milieu isotonique (normal), hypotonique (turgescence, hémolyse) et hypertonique (aspect crénelé).', 'premiere-c-svt-2', 'premiere-c-svt-2-s2', 6),
('premiere-c-svt-2-s2-l3', 'État des cellules végétales et phénomènes associés', 'Cellules d''épiderme d''oignon : aspect normal, turgescence, plasmolyse en milieux différents, et déplasmolyse.', 'premiere-c-svt-2', 'premiere-c-svt-2-s2', 7),
('premiere-c-svt-2-s2-l4', 'Le mécanisme d''échange d''eau : l''osmose', 'Principe de l''osmose, expérience de Dutrochet avec membrane hémiperméable et calcul de la pression osmotique.', 'premiere-c-svt-2', 'premiere-c-svt-2-s2', 8),
('premiere-c-svt-2-s2-l5', 'Le mécanisme d''échange des substances dissoutes', 'Transport passif (diffusion libre et facilitée par perméases) et transport actif contre le gradient avec apport d''énergie.', 'premiere-c-svt-2', 'premiere-c-svt-2-s2', 9),
('premiere-c-svt-2-s2-l6', 'Importance biologique et domaines d''application des échanges cellulaires', 'Échanges de matière et d''énergie ; applications en médecine (hémodialyse, sérums) et en agronomie (intrants).', 'premiere-c-svt-2', 'premiere-c-svt-2-s2', 10),
('premiere-c-svt-2-s3-l1', 'Les chromosomes', 'Définition de la mitose et de la méiose, localisation des chromosomes, structure d''un chromosome et caryotype.', 'premiere-c-svt-2', 'premiere-c-svt-2-s3', 11),
('premiere-c-svt-2-s3-l2', 'Les étapes de la mitose', 'Déroulement de la mitose : prophase, métaphase, anaphase et télophase.', 'premiere-c-svt-2', 'premiere-c-svt-2-s3', 12),
('premiere-c-svt-2-s3-l3', 'Les étapes de la méiose et comparaison avec la mitose', 'Divisions réductionnelle et équationnelle ; points communs et différences entre mitose et méiose.', 'premiere-c-svt-2', 'premiere-c-svt-2-s3', 13),
('premiere-c-svt-2-s3-l4', 'Le cycle cellulaire et son contrôle', 'Interphase (G1, S, G2) et mitose ; déterminisme et inhibition (colchicine, rayonnements), traitement des cancers, polyploïdie.', 'premiere-c-svt-2', 'premiere-c-svt-2-s3', 14),
('premiere-c-svt-2-s3-l5', 'Facteurs de risque des anomalies des divisions cellulaires', 'Facteurs des divisions anarchiques (cancers), modifiables et non modifiables, et facteurs des anomalies chromosomiques.', 'premiere-c-svt-2', 'premiere-c-svt-2-s3', 15),
('premiere-c-svt-2-s3-l6', 'Importance biologique de la mitose et de la méiose', 'Mitose : croissance, renouvellement, conservation génétique. Méiose : formation des gamètes, brassage et diversité.', 'premiere-c-svt-2', 'premiere-c-svt-2-s3', 16),
('premiere-c-svt-3-s1-l1', 'Mise en évidence et mesure des échanges gazeux respiratoires', 'Absorption du dioxygène, dégagement du dioxyde de carbone, mesure des volumes et calcul de l''intensité et du quotient respiratoires.', 'premiere-c-svt-3', 'premiere-c-svt-3-s1', 1),
('premiere-c-svt-3-s1-l2', 'Le transport sanguin des gaz respiratoires', 'Structure de l''hémoglobine et formes de transport du dioxygène et du dioxyde de carbone dans le sang.', 'premiere-c-svt-3', 'premiere-c-svt-3-s1', 2),
('premiere-c-svt-3-s1-l3', 'Le mécanisme de la respiration cellulaire', 'Métabolisme, anabolisme, catabolisme, ATP ; étapes de la dégradation du glucose et équation-bilan énergétique.', 'premiere-c-svt-3', 'premiere-c-svt-3-s1', 3),
('premiere-c-svt-3-s1-l4', 'Maladies respiratoires et leurs facteurs de risque', 'Tuberculose, asthme, cancer du poumon et autres ; tabac, alcool, pesticides, infections et pollution comme facteurs de risque.', 'premiere-c-svt-3', 'premiere-c-svt-3-s1', 4),
('premiere-c-svt-3-s2-l1', 'Les fermentations alcoolique et acétique', 'Oxydations incomplètes en milieu anaérobie ou aérobie ; équations de transformation du glucose en éthanol et du vin en vinaigre.', 'premiere-c-svt-3', 'premiere-c-svt-3-s2', 5),
('premiere-c-svt-3-s2-l2', 'Les autres formes de fermentation', 'Fermentations lactique, butyrique, propionique et fermentation du sol (humification, ammonisation, nitrification).', 'premiere-c-svt-3', 'premiere-c-svt-3-s2', 6),
('premiere-c-svt-3-s2-l3', 'Comparaison de la fermentation alcoolique et de la respiration', 'Points communs (glucose, acide pyruvique, dégagement de CO2) et différences (oxygène, rendement en ATP, siège cellulaire).', 'premiere-c-svt-3', 'premiere-c-svt-3-s2', 7),
('premiere-c-svt-3-s2-l4', 'Les avantages des fermentations', 'Production de bière, pain, yaourts, fromage, moutarde africaine, lanhouin et biogaz ; fertilisation des sols.', 'premiere-c-svt-3', 'premiere-c-svt-3-s2', 8),
('premiere-c-svt-3-s3-l1', 'Les domaines d''usage de la matière organique par l''Homme', 'Alimentation, habillement, ameublement, médecine, cosmétique, industrie, construction, sculpture et papeterie.', 'premiere-c-svt-3', 'premiere-c-svt-3-s3', 9),
('premiere-c-svt-3-s3-l2', 'Le cycle du carbone dans la nature', 'Établissement et description des étapes du cycle du carbone dans la nature.', 'premiere-c-svt-3', 'premiere-c-svt-3-s3', 10),
('premiere-c-svt-3-s3-l3', 'Le cycle de l''azote dans la nature', 'Établissement et description des étapes du cycle de l''azote dans la nature.', 'premiere-c-svt-3', 'premiere-c-svt-3-s3', 11),
('premiere-c-svt-3-s3-l4', 'Avantages et effets néfastes des transformations de la matière', 'Avantages : conservation, biocarburants, biogaz, fertilisation. Effets néfastes : pollutions et gaz à effet de serre.', 'premiere-c-svt-3', 'premiere-c-svt-3-s3', 12),
('premiere-d-svt-1-s1-l1', 'Les plaques lithosphériques', 'Distinction entre plaques océaniques (Pacifique, Antarctique) et plaques continentales (Africaine, Sud-Américaine, Eurasienne, Indienne, etc.).', 'premiere-d-svt-1', 'premiere-d-svt-1-s1', 1),
('premiere-d-svt-1-s1-l2', 'La théorie de Wegener et la dérive des continents', 'Comparaison des positions actuelles et passées des continents pour énoncer la théorie de la dérive des continents (Wegener, 1912).', 'premiere-d-svt-1', 'premiere-d-svt-1-s1', 2),
('premiere-d-svt-1-s1-l3', 'Les arguments en faveur de la théorie de Wegener', 'Arguments morphologiques, stratigraphiques, paléontologiques et pétrographiques appuyant la dérive des continents.', 'premiere-d-svt-1', 'premiere-d-svt-1-s1', 3),
('premiere-d-svt-1-s1-l4', 'La théorie de Hess et l''expansion océanique', 'Analyse des cartes des fonds océaniques et énoncé de la théorie de l''expansion des fonds océaniques (Hess).', 'premiere-d-svt-1', 'premiere-d-svt-1-s1', 4),
('premiere-d-svt-1-s1-l5', 'Les arguments en faveur de la théorie de Hess', 'Disposition des sédiments, âge et symétrie des basaltes, répartition des anomalies magnétiques par rapport au rift.', 'premiere-d-svt-1', 'premiere-d-svt-1-s1', 5),
('premiere-d-svt-1-s1-l6', 'Les mouvements des plaques, leurs causes et conséquences', 'Divergence, convergence, coulissage; subduction, obduction, collision; causes (radioactivité, convection, pression lithostatique).', 'premiere-d-svt-1', 'premiere-d-svt-1-s1', 6),
('premiere-d-svt-1-s2-l1', 'Les différentes formations géologiques du Togo', 'Bassin côtier, chaîne des Dahoméyides, bassin des Volta, socle Birrimien et leurs roches (granite, phosphate, calcaire, marbre).', 'premiere-d-svt-1', 'premiere-d-svt-1-s2', 7),
('premiere-d-svt-1-s2-l2', 'Les grandes étapes de l''histoire géologique du Togo', 'Roches anciennes, orogenèse éburnéenne, glaciation et transgression, orogenèse panafricaine, ouverture de l''Atlantique.', 'premiere-d-svt-1', 'premiere-d-svt-1-s2', 8),
('premiere-d-svt-1-s2-l3', 'La géologie du Togo dans le contexte ouest-africain', 'Zones stable et mobile, bassins ancien et récent, en lien avec le craton ouest-africain et les Dahoméyides.', 'premiere-d-svt-1', 'premiere-d-svt-1-s2', 9),
('premiere-d-svt-1-s2-l4', 'La localisation des principaux minerais', 'Bassin côtier (calcaire, phosphate, pétrole), Buem (fer, phosphate) et Atacora (marbre) sur une carte.', 'premiere-d-svt-1', 'premiere-d-svt-1-s2', 10),
('premiere-d-svt-2-s1-l1', 'Les constituants minéraux et organiques', 'Constituants minéraux (eau, sels minéraux) et constituants organiques (glucides, protides, lipides) de la matière vivante.', 'premiere-d-svt-2', 'premiere-d-svt-2-s1', 1),
('premiere-d-svt-2-s1-l2', 'Le calcul de la teneur en eau', 'Calcul de la teneur en eau d''un organe ou d''un organisme par rapport à la masse fraîche.', 'premiere-d-svt-2', 'premiere-d-svt-2-s1', 2),
('premiere-d-svt-2-s1-l3', 'Les rôles de l''eau dans la matière vivante', 'Rôles de solvant, plastique, thermorégulateur, de transport des substances et osmorégulateur.', 'premiere-d-svt-2', 'premiere-d-svt-2-s1', 3),
('premiere-d-svt-2-s1-l4', 'Les propriétés des substances organiques', 'Propriétés et composition des glucides, protides et lipides; application à la fabrication des savons.', 'premiere-d-svt-2', 'premiere-d-svt-2-s1', 4),
('premiere-d-svt-2-s1-l5', 'Les différents types de solutions', 'Réalisation d''une solution vraie, d''une solution colloïdale, d''une suspension et d''une émulsion.', 'premiere-d-svt-2', 'premiere-d-svt-2-s1', 5),
('premiere-d-svt-3-s1-l1', 'La structure générale de la cellule', 'Cellule observée au microscope optique et électronique; cellules eucaryotes et procaryotes.', 'premiere-d-svt-3', 'premiere-d-svt-3-s1', 1),
('premiere-d-svt-3-s1-l2', 'Les parties et les organites de la cellule', 'Membrane, paroi, vacuoles, cytoplasme, réticulum, appareil de Golgi, mitochondries, chloroplastes, noyau, centrosome.', 'premiere-d-svt-3', 'premiere-d-svt-3-s1', 2),
('premiere-d-svt-3-s1-l3', 'Comparaison de la cellule animale et de la cellule végétale', 'Points communs (noyau, mitochondrie, réticulums, Golgi) et différences (plastes, centrosome, vacuoles, paroi).', 'premiere-d-svt-3', 'premiere-d-svt-3-s1', 3),
('premiere-d-svt-3-s1-l4', 'Le rôle des parties et des organites de la cellule', 'Fonction de la membrane, de la paroi, des vacuoles, du cytoplasme, des organites et du noyau.', 'premiere-d-svt-3', 'premiere-d-svt-3-s1', 4),
('premiere-d-svt-3-s2-l1', 'Exemples d''échanges cellulaires', 'Absorption racinaire, échanges gazeux chlorophylliens et respiratoires, absorption intestinale.', 'premiere-d-svt-3', 'premiere-d-svt-3-s2', 5),
('premiere-d-svt-3-s2-l2', 'L''état des cellules dans des solutions de concentrations différentes', 'Comportement des globules rouges et des cellules d''oignon en milieux isotonique, hypotonique et hypertonique.', 'premiere-d-svt-3', 'premiere-d-svt-3-s2', 6),
('premiere-d-svt-3-s2-l3', 'L''osmose et l''échange d''eau', 'Principe de l''osmose, expérience de Dutrochet et calcul de la pression osmotique.', 'premiere-d-svt-3', 'premiere-d-svt-3-s2', 7),
('premiere-d-svt-3-s2-l4', 'Les échanges de substances dissoutes', 'Transport passif (diffusion libre et facilitée) et transport actif contre le gradient de concentration.', 'premiere-d-svt-3', 'premiere-d-svt-3-s2', 8),
('premiere-d-svt-3-s2-l5', 'Les échanges de particules', 'Endocytose (phagocytose, pinocytose) et exocytose par les cellules.', 'premiere-d-svt-3', 'premiere-d-svt-3-s2', 9),
('premiere-d-svt-3-s2-l6', 'Importance et domaines d''application des échanges cellulaires', 'Échanges de matières et d''énergie; applications en médecine (hémodialyse, sérums) et en agronomie (intrants).', 'premiere-d-svt-3', 'premiere-d-svt-3-s2', 10),
('premiere-d-svt-3-s3-l1', 'Chromosomes et caryotype', 'Définition de la mitose et de la méiose, localisation et structure d''un chromosome, réalisation d''un caryotype.', 'premiere-d-svt-3', 'premiere-d-svt-3-s3', 11),
('premiere-d-svt-3-s3-l2', 'Les étapes de la mitose et de la méiose', 'Prophase, métaphase, anaphase, télophase; divisions réductionnelle et équationnelle de la méiose.', 'premiere-d-svt-3', 'premiere-d-svt-3-s3', 12),
('premiere-d-svt-3-s3-l3', 'Comparaison de la mitose et de la méiose', 'Points communs et différences, dont les tétrades, le clivage des centromères et la conformité de la reproduction.', 'premiere-d-svt-3', 'premiere-d-svt-3-s3', 13),
('premiere-d-svt-3-s3-l4', 'Le cycle cellulaire et son contrôle', 'Interphase (G1, S, G2) et mitose; déterminisme, inhibiteurs, traitement des cancers, organismes polyploïdes.', 'premiere-d-svt-3', 'premiere-d-svt-3-s3', 14),
('premiere-d-svt-3-s3-l5', 'Les facteurs de risque des anomalies des divisions cellulaires', 'Facteurs des divisions anarchiques (cancers) modifiables et non modifiables, et des anomalies chromosomiques.', 'premiere-d-svt-3', 'premiere-d-svt-3-s3', 15),
('premiere-d-svt-3-s3-l6', 'L''importance de la mitose et de la méiose', 'Croissance et renouvellement cellulaire; formation des gamètes, brassage et diversification génétique.', 'premiere-d-svt-3', 'premiere-d-svt-3-s3', 16),
('premiere-d-svt-4-s1-l1', 'Les échanges gazeux respiratoires', 'Mise en évidence de l''absorption du dioxygène et du rejet du CO2; calcul des volumes, intensité et quotient respiratoires.', 'premiere-d-svt-4', 'premiere-d-svt-4-s1', 1),
('premiere-d-svt-4-s1-l2', 'Le transport sanguin des gaz respiratoires', 'Structure de l''hémoglobine et formes de transport du dioxygène et du dioxyde de carbone dans le sang.', 'premiere-d-svt-4', 'premiere-d-svt-4-s1', 2),
('premiere-d-svt-4-s1-l3', 'Le mécanisme de la respiration cellulaire', 'Métabolisme, anabolisme, catabolisme, ATP; étapes et bilan énergétique de la dégradation du glucose.', 'premiere-d-svt-4', 'premiere-d-svt-4-s1', 3),
('premiere-d-svt-4-s1-l4', 'Les maladies respiratoires et leurs facteurs de risque', 'Tuberculose, asthme, cancer du poumon; facteurs de risque comme tabac, pollution et allergènes.', 'premiere-d-svt-4', 'premiere-d-svt-4-s1', 4),
('premiere-d-svt-4-s2-l1', 'La fermentation alcoolique et la fermentation acétique', 'Conditions et équations de la transformation du glucose en éthanol et de l''alcool en vinaigre.', 'premiere-d-svt-4', 'premiere-d-svt-4-s2', 5),
('premiere-d-svt-4-s2-l2', 'Les autres formes de fermentation', 'Fermentations lactique, butyrique, propionique et fermentation du sol (humification, ammonisation, nitrification).', 'premiere-d-svt-4', 'premiere-d-svt-4-s2', 6),
('premiere-d-svt-4-s2-l3', 'Comparaison de la fermentation alcoolique et de la respiration', 'Points communs (glucose, acide pyruvique, CO2) et différences d''oxydation, de siège et de rendement en ATP.', 'premiere-d-svt-4', 'premiere-d-svt-4-s2', 7),
('premiere-d-svt-4-s2-l4', 'Avantages et inconvénients des fermentations', 'Production de boissons, pain, yaourt, biogaz; risques d''intoxication alimentaire et de perte d''aliments.', 'premiere-d-svt-4', 'premiere-d-svt-4-s2', 8),
('premiere-d-svt-4-s3-l1', 'Les domaines d''usage de la matière organique', 'Alimentation, habillement, médecine, cosmétique, industrie, construction et autres usages par l''Homme.', 'premiere-d-svt-4', 'premiere-d-svt-4-s3', 9),
('premiere-d-svt-4-s3-l2', 'Le cycle du carbone et le cycle de l''azote', 'Établissement des cycles du carbone et de l''azote dans la nature.', 'premiere-d-svt-4', 'premiere-d-svt-4-s3', 10),
('premiere-d-svt-4-s3-l3', 'Avantages et inconvénients des transformations de la matière organique', 'Conservation, biocarburants, biogaz, fertilisation; pollutions et gaz à effet de serre.', 'premiere-d-svt-4', 'premiere-d-svt-4-s3', 11),
('premiere-d-svt-4-s3-l4', 'Les méthodes de conservation des aliments', 'Fumage, congélation, salaison, séchage, conservation par chauffage et par fermentation.', 'premiere-d-svt-4', 'premiere-d-svt-4-s3', 12),
('terminale-svt-1-s1-l1', 'Structure de l''ADN', 'Composition de l''ADN en nucléotides et organisation en double hélice.', 'terminale-svt-1', 'terminale-svt-1-s1', 1),
('terminale-svt-1-s1-l2', 'La duplication de l''ADN', 'Mécanisme de réplication de la molécule d''ADN.', 'terminale-svt-1', 'terminale-svt-1-s1', 2),
('terminale-svt-1-s1-l3', 'Structure et types d''ARN', 'Nucléotides et simple hélice de l''ARN, et les différents types d''ARN.', 'terminale-svt-1', 'terminale-svt-1-s1', 3),
('terminale-svt-1-s1-l4', 'La transcription de l''ADN en ARN', 'Passage de l''information de l''ADN vers l''ARN par transcription.', 'terminale-svt-1', 'terminale-svt-1-s1', 4),
('terminale-svt-1-s1-l5', 'Comparaison de l''ADN et de l''ARN', 'Ressemblances et différences de structure, de composition et de longueur entre ADN et ARN.', 'terminale-svt-1', 'terminale-svt-1-s1', 5),
('terminale-svt-1-s1-l6', 'Monohybridisme et lois de Mendel', 'Transmission d''un couple d''allèles par autosome (1ere et 2e lois) et hérédité liée au sexe.', 'terminale-svt-1', 'terminale-svt-1-s1', 6),
('terminale-svt-1-s1-l7', 'Dihybridisme et gènes indépendants', 'Transmission de deux couples d''allèles par des paires différentes de chromosomes (3e loi de Mendel).', 'terminale-svt-1', 'terminale-svt-1-s1', 7),
('terminale-svt-1-s2-l1', 'Le pédigrée : réalisation et analyse', 'Symboles de l''arbre généalogique, réalisation d''un pédigrée et repérage des sujets sains et malades.', 'terminale-svt-1', 'terminale-svt-1-s2', 8),
('terminale-svt-1-s2-l2', 'Transmission d''un gène par un autosome', 'Hérédité autosomale illustrée par la drépanocytose et les groupes sanguins.', 'terminale-svt-1', 'terminale-svt-1-s2', 9),
('terminale-svt-1-s2-l3', 'Transmission d''un gène par un gonosome', 'Hérédité liée au sexe illustrée par le daltonisme, la polydactylie et l''hémophilie.', 'terminale-svt-1', 'terminale-svt-1-s2', 10),
('terminale-svt-1-s2-l4', 'Prévention des maladies géniques', 'Électrophorèse et recherche de généalogie avant le mariage, et prohibition des mariages consanguins.', 'terminale-svt-1', 'terminale-svt-1-s2', 11),
('terminale-svt-2-s1-l1', 'Les gonades et la gamétogenèse', 'Coupe des gonades (testicule, ovaire), définition et localisation de la gamétogenèse.', 'terminale-svt-2', 'terminale-svt-2-s1', 1),
('terminale-svt-2-s1-l2', 'Les étapes de la gamétogenèse', 'Phases de multiplication, accroissement, maturation et différenciation.', 'terminale-svt-2', 'terminale-svt-2-s1', 2),
('terminale-svt-2-s1-l3', 'Comparaison spermatogenèse et ovogenèse', 'Comparaison du début, de la période, du nombre d''étapes et de gamètes formés.', 'terminale-svt-2', 'terminale-svt-2-s1', 3),
('terminale-svt-2-s1-l4', 'Courbe de la quantité d''ADN', 'Construction et interprétation de la courbe de variation de l''ADN au cours de la gamétogenèse.', 'terminale-svt-2', 'terminale-svt-2-s1', 4),
('terminale-svt-2-s1-l5', 'La fécondation', 'Conditions, étapes et importance de la fécondation.', 'terminale-svt-2', 'terminale-svt-2-s1', 5),
('terminale-svt-2-s1-l6', 'Segmentation, migration et implantation de l''œuf', 'Devenir de l''œuf de la segmentation jusqu''à son implantation.', 'terminale-svt-2', 'terminale-svt-2-s1', 6),
('terminale-svt-3-s1-l1', 'Le soi et le non-soi', 'Distinction entre le soi et le non-soi de l''organisme.', 'terminale-svt-3', 'terminale-svt-3-s1', 1),
('terminale-svt-3-s1-l2', 'Les composants du système immunitaire', 'Barrières, organes lymphoïdes et cellules immunitaires du système immunitaire.', 'terminale-svt-3', 'terminale-svt-3-s1', 2),
('terminale-svt-3-s1-l3', 'Déterminants moléculaires et anticorps', 'Déterminants du soi et du non-soi, structure et types d''anticorps (IgA, IgM, IgG, IgE, IgD).', 'terminale-svt-3', 'terminale-svt-3-s1', 3),
('terminale-svt-3-s1-l4', 'La réponse immunitaire innée', 'Moyens de défense non spécifiques : barrières, réaction inflammatoire et phagocytose.', 'terminale-svt-3', 'terminale-svt-3-s1', 4),
('terminale-svt-3-s1-l5', 'La réponse immunitaire adaptative', 'Réponses spécifiques à médiation humorale et à médiation cellulaire.', 'terminale-svt-3', 'terminale-svt-3-s1', 5),
('terminale-svt-3-s1-l6', 'Applications de l''immunologie', 'Tests de grossesse, groupes sanguins, dépistage des cancers, vaccins et sérums.', 'terminale-svt-3', 'terminale-svt-3-s1', 6),
('terminale-svt-3-s2-l1', 'Structure du tissu cardiaque', 'Tissu musculaire cardiaque (myocarde) et tissu nodal du cœur.', 'terminale-svt-3', 'terminale-svt-3-s2', 7),
('terminale-svt-3-s2-l2', 'L''automatisme cardiaque et le cardiogramme', 'Siège et origine de l''automatisme, analyse du cardiogramme et du potentiel d''action.', 'terminale-svt-3', 'terminale-svt-3-s2', 8),
('terminale-svt-3-s2-l3', 'Action des substances chimiques sur le cœur', 'Effets de substances comme acétylcholine, adrénaline et ions sur le rythme cardiaque.', 'terminale-svt-3', 'terminale-svt-3-s2', 9),
('terminale-svt-3-s2-l4', 'La tension artérielle et ses variations', 'Notions de tension, d''hypertension et d''hypotension artérielle.', 'terminale-svt-3', 'terminale-svt-3-s2', 10),
('terminale-svt-3-s2-l5', 'Prévention de l''hypertension et de l''hypotension', 'Mesures de prévention de l''hypertension et de l''hypotension artérielles.', 'terminale-svt-3', 'terminale-svt-3-s2', 11),
('terminale-c-svt-1-s1-l1', 'Structure et duplication de l''ADN', 'Nucléotides et double hélice de l''ADN, puis mécanisme de sa duplication.', 'terminale-c-svt-1', 'terminale-c-svt-1-s1', 1),
('terminale-c-svt-1-s1-l2', 'Structure et types d''ARN, comparaison avec l''ADN', 'ARN simple hélice, ses différents types, puis comparaison de l''ADN et de l''ARN.', 'terminale-c-svt-1', 'terminale-c-svt-1-s1', 2),
('terminale-c-svt-1-s1-l3', 'La synthèse des protéines', 'Transcription de l''ADN en ARNm et traduction : codons, code génétique, initiation, élongation, terminaison.', 'terminale-c-svt-1', 'terminale-c-svt-1-s1', 3),
('terminale-c-svt-1-s1-l4', 'Le monohybridisme et les lois de Mendel', 'Transmission d''un couple d''allèles par autosome (1re et 2e loi) et exception liée au sexe.', 'terminale-c-svt-1', 'terminale-c-svt-1-s1', 4),
('terminale-c-svt-1-s1-l5', 'Le dihybridisme', 'Transmission de deux couples d''allèles par des chromosomes différents : gènes indépendants, 3e loi de Mendel.', 'terminale-c-svt-1', 'terminale-c-svt-1-s1', 5),
('terminale-c-svt-1-s1-l6', 'Les domaines d''application de la génétique', 'Le génie génétique appliqué au secteur agroalimentaire et à la santé.', 'terminale-c-svt-1', 'terminale-c-svt-1-s1', 6),
('terminale-c-svt-1-s2-l1', 'Réaliser et analyser un pédigrée', 'Construire un arbre généalogique et repérer les sujets sains, porteurs et malades.', 'terminale-c-svt-1', 'terminale-c-svt-1-s2', 7),
('terminale-c-svt-1-s2-l2', 'Transmission d''un gène par un autosome', 'Cas de la polydactylie, de la drépanocytose et des groupes sanguins.', 'terminale-c-svt-1', 'terminale-c-svt-1-s2', 8),
('terminale-c-svt-1-s2-l3', 'Transmission d''un gène par un gonosome', 'Hérédité liée au sexe : exemples du daltonisme et de l''hémophilie.', 'terminale-c-svt-1', 'terminale-c-svt-1-s2', 9),
('terminale-c-svt-1-s2-l4', 'La prévention des maladies géniques', 'Électrophorèse et recherche de généalogie avant mariage, prohibition des mariages consanguins.', 'terminale-c-svt-1', 'terminale-c-svt-1-s2', 10),
('terminale-c-svt-2-s1-l1', 'Les gonades et les phases de la gamétogenèse', 'Coupe des gonades, définition et localisation, phases : multiplication, accroissement, maturation, différenciation.', 'terminale-c-svt-2', 'terminale-c-svt-2-s1', 1),
('terminale-c-svt-2-s1-l2', 'Comparaison de la spermatogenèse et de l''ovogenèse', 'Comparaison des deux processus et courbe de variation de la quantité d''ADN au cours de la gamétogenèse.', 'terminale-c-svt-2', 'terminale-c-svt-2-s1', 2),
('terminale-c-svt-2-s1-l3', 'La fécondation', 'Conditions de la fécondation, ses étapes et son importance.', 'terminale-c-svt-2', 'terminale-c-svt-2-s1', 3),
('terminale-c-svt-2-s1-l4', 'De la segmentation à l''implantation de l''œuf', 'Segmentation, migration puis implantation de l''œuf.', 'terminale-c-svt-2', 'terminale-c-svt-2-s1', 4),
('terminale-c-svt-3-s1-l1', 'Organisation du système nerveux et de la moelle épinière', 'Schéma de synthèse du système nerveux et identification des éléments de la moelle épinière.', 'terminale-c-svt-3', 'terminale-c-svt-3-s1', 1),
('terminale-c-svt-3-s1-l2', 'Structure du nerf et du neurone', 'Organisation structurale d''un nerf et représentation annotée d''un neurone.', 'terminale-c-svt-3', 'terminale-c-svt-3-s1', 2),
('terminale-c-svt-3-s1-l3', 'Excitabilité et potentiel de repos', 'Propriété d''excitabilité du tissu nerveux, origine et maintien du potentiel de repos.', 'terminale-c-svt-3', 'terminale-c-svt-3-s1', 3),
('terminale-c-svt-3-s1-l4', 'Le potentiel d''action', 'Enregistrement, analyse et interprétation du potentiel d''action d''une fibre et d''un nerf.', 'terminale-c-svt-3', 'terminale-c-svt-3-s1', 4),
('terminale-c-svt-3-s1-l5', 'La conductibilité de l''influx nerveux', 'Vitesse, mode et sens de conduction, propagation dans les fibres avec et sans myéline.', 'terminale-c-svt-3', 'terminale-c-svt-3-s1', 5),
('terminale-c-svt-3-s1-l6', 'Les effets nocifs des drogues', 'Effet des drogues sur le système nerveux et méfaits sur l''individu et la société.', 'terminale-c-svt-3', 'terminale-c-svt-3-s1', 6),
('terminale-c-svt-4-s1-l1', 'Le soi, le non soi et le système immunitaire', 'Notions de soi et de non soi, composants du système immunitaire et déterminants moléculaires.', 'terminale-c-svt-4', 'terminale-c-svt-4-s1', 1),
('terminale-c-svt-4-s1-l2', 'La réponse immunitaire innée', 'Rôle des barrières, réaction inflammatoire et étapes de la phagocytose.', 'terminale-c-svt-4', 'terminale-c-svt-4-s1', 2),
('terminale-c-svt-4-s1-l3', 'La réponse immunitaire adaptative', 'Réactions à médiation humorale et cellulaire, existence de la mémoire immunitaire.', 'terminale-c-svt-4', 'terminale-c-svt-4-s1', 3),
('terminale-c-svt-4-s1-l4', 'Applications : grossesse, groupes sanguins et transfusion', 'Principe du test de grossesse, détermination des groupes sanguins et possibilités de transfusion.', 'terminale-c-svt-4', 'terminale-c-svt-4-s1', 4),
('terminale-c-svt-4-s1-l5', 'Applications : dépistages, vaccins et sérum', 'Dépistages des cancers, du VIH et de la COVID, puis rôle des vaccins et du sérum.', 'terminale-c-svt-4', 'terminale-c-svt-4-s1', 5),
('terminale-c-svt-4-s2-l1', 'Les tissus cardiaques', 'Tissu musculaire cardiaque (myocarde) et tissu nodal, schéma de la coupe du cœur.', 'terminale-c-svt-4', 'terminale-c-svt-4-s2', 6),
('terminale-c-svt-4-s2-l2', 'L''automatisme cardiaque', 'Mise en évidence de l''automatisme, son siège dans le tissu nodal et son origine.', 'terminale-c-svt-4', 'terminale-c-svt-4-s2', 7),
('terminale-c-svt-4-s2-l3', 'Action du système nerveux et des substances chimiques', 'Innervation cardiaque et action de substances comme l''acétylcholine et l''adrénaline sur le rythme.', 'terminale-c-svt-4', 'terminale-c-svt-4-s2', 8),
('terminale-c-svt-4-s2-l4', 'La tension artérielle', 'Notions de tension ou pression artérielle, d''hypertension et d''hypotension artérielles.', 'terminale-c-svt-4', 'terminale-c-svt-4-s2', 9),
('terminale-c-svt-4-s2-l5', 'Prévention de l''hypertension et de l''hypotension', 'Mesures d''hygiène de vie pour prévenir l''hypertension et l''hypotension artérielles.', 'terminale-c-svt-4', 'terminale-c-svt-4-s2', 10),
('terminale-d-svt-1-s1-l1', 'Structure et duplication de l''ADN', 'Les nucléotides, la double hélice de l''ADN et le mécanisme de la duplication.', 'terminale-d-svt-1', 'terminale-d-svt-1-s1', 1),
('terminale-d-svt-1-s1-l2', 'L''ARN et sa comparaison avec l''ADN', 'Structure de l''ARN en simple hélice, ses différents types, et sa comparaison avec l''ADN.', 'terminale-d-svt-1', 'terminale-d-svt-1-s1', 2),
('terminale-d-svt-1-s1-l3', 'La synthèse des protéines', 'Transcription de l''ADN en ARNm puis traduction : codons, code génétique, initiation, élongation, terminaison.', 'terminale-d-svt-1', 'terminale-d-svt-1-s1', 3),
('terminale-d-svt-1-s1-l4', 'Mutations et maladies géniques', 'Mutations par substitution, inversion, délétion et insertion et les maladies associées.', 'terminale-d-svt-1', 'terminale-d-svt-1-s1', 4),
('terminale-d-svt-1-s1-l5', 'Monohybridisme et lois de Mendel', 'Transmission d''un couple d''allèles, 1re et 2e lois, hérédité liée au sexe et gène létal.', 'terminale-d-svt-1', 'terminale-d-svt-1-s1', 5),
('terminale-d-svt-1-s1-l6', 'Dihybridisme et applications de la génétique', '3e loi de Mendel, gènes liés, crossing over, carte factorielle et applications du génie génétique.', 'terminale-d-svt-1', 'terminale-d-svt-1-s1', 6),
('terminale-d-svt-1-s2-l1', 'Construire et analyser un pédigrée', 'Réalisation d''un arbre généalogique et identification des sujets sains, porteurs et malades.', 'terminale-d-svt-1', 'terminale-d-svt-1-s2', 7),
('terminale-d-svt-1-s2-l2', 'Transmission autosomique et gonosomique', 'Modes de transmission d''un gène par un autosome ou un gonosome à travers des exemples.', 'terminale-d-svt-1', 'terminale-d-svt-1-s2', 8),
('terminale-d-svt-1-s2-l3', 'Les aberrations chromosomiques', 'Anomalies liées aux autosomes (trisomies, monosomies) et aux gonosomes (Turner, Klinefelter).', 'terminale-d-svt-1', 'terminale-d-svt-1-s2', 9),
('terminale-d-svt-1-s2-l4', 'Prévention des maladies géniques', 'Électrophorèse avant mariage, recherche de généalogie et prohibition des mariages consanguins.', 'terminale-d-svt-1', 'terminale-d-svt-1-s2', 10),
('terminale-d-svt-2-s1-l1', 'Les étapes de la gamétogenèse', 'Coupe des gonades et phases de multiplication, accroissement, maturation et différenciation.', 'terminale-d-svt-2', 'terminale-d-svt-2-s1', 1),
('terminale-d-svt-2-s1-l2', 'Comparaison spermatogenèse et ovogenèse', 'Différences entre les deux processus et courbe de variation de la quantité d''ADN.', 'terminale-d-svt-2', 'terminale-d-svt-2-s1', 2),
('terminale-d-svt-2-s1-l3', 'La régulation hormonale des gonades', 'Relation hypothalamo-hypophysaire, hormones impliquées et rétrocontrôle hormonal.', 'terminale-d-svt-2', 'terminale-d-svt-2-s1', 3),
('terminale-d-svt-2-s1-l4', 'Les cycles sexuels chez la femme', 'Cycle ovarien, utérin, de la glaire cervicale, mammaire, thermique et hormonal.', 'terminale-d-svt-2', 'terminale-d-svt-2-s1', 4),
('terminale-d-svt-2-s2-l1', 'De la fécondation à l''implantation', 'Conditions et étapes de la fécondation, segmentation, migration et implantation de l''œuf.', 'terminale-d-svt-2', 'terminale-d-svt-2-s2', 5),
('terminale-d-svt-2-s2-l2', 'La gestation et la parturition', 'Étapes de la grossesse, rôles des annexes embryonnaires et déclenchement de l''accouchement.', 'terminale-d-svt-2', 'terminale-d-svt-2-s2', 6),
('terminale-d-svt-2-s2-l3', 'La lactation', 'Production du lait maternel par les lactocytes et mécanisme de son éjection.', 'terminale-d-svt-2', 'terminale-d-svt-2-s2', 7),
('terminale-d-svt-2-s2-l4', 'Stérilité, contraception et perturbateurs endocriniens', 'Causes de la stérilité, principes de la contraception et effets des perturbateurs endocriniens.', 'terminale-d-svt-2', 'terminale-d-svt-2-s2', 8),
('terminale-d-svt-2-s3-l1', 'Organisation d''une fleur', 'Organisation générale de la fleur et structure de l''anthère et de l''ovule.', 'terminale-d-svt-2', 'terminale-d-svt-2-s3', 9),
('terminale-d-svt-2-s3-l2', 'Formation du pollen et du sac embryonnaire', 'Étapes de la formation des grains de pollen et du sac embryonnaire.', 'terminale-d-svt-2', 'terminale-d-svt-2-s3', 10),
('terminale-d-svt-2-s3-l3', 'Pollinisation et double fécondation', 'Pollinisation, germination du grain de pollen et double fécondation chez les Spermaphytes.', 'terminale-d-svt-2', 'terminale-d-svt-2-s3', 11),
('terminale-d-svt-2-s3-l4', 'La formation de la graine', 'Étapes de la formation de la graine et origine de ses différentes parties.', 'terminale-d-svt-2', 'terminale-d-svt-2-s3', 12),
('terminale-d-svt-3-s1-l1', 'Organisation du système nerveux', 'Organisation générale du système nerveux, de la moelle épinière et structure du nerf.', 'terminale-d-svt-3', 'terminale-d-svt-3-s1', 1),
('terminale-d-svt-3-s1-l2', 'Les propriétés du tissu nerveux', 'Le neurone, l''excitabilité, le potentiel de repos, le potentiel d''action et la conductibilité.', 'terminale-d-svt-3', 'terminale-d-svt-3-s1', 2),
('terminale-d-svt-3-s1-l3', 'La transmission synaptique', 'Ultrastructure d''une synapse chimique, mécanisme de transmission et intégration neuronale.', 'terminale-d-svt-3', 'terminale-d-svt-3-s1', 3),
('terminale-d-svt-3-s1-l4', 'Effets des drogues sur le système nerveux', 'Mode d''action de quelques substances chimiques et effets nocifs des drogues.', 'terminale-d-svt-3', 'terminale-d-svt-3-s1', 4),
('terminale-d-svt-3-s2-l1', 'Organisation anatomique du muscle', 'Structure macroscopique du muscle, microscopique de la fibre et synapses neuromusculaires.', 'terminale-d-svt-3', 'terminale-d-svt-3-s2', 5),
('terminale-d-svt-3-s2-l2', 'La plaque motrice', 'Structure et fonctionnement de la plaque motrice.', 'terminale-d-svt-3', 'terminale-d-svt-3-s2', 6),
('terminale-d-svt-3-s2-l3', 'Le réflexe myotatique', 'Relation fonctionnelle entre tissu nerveux et muscle et importance des réflexes myotatiques.', 'terminale-d-svt-3', 'terminale-d-svt-3-s2', 7),
('terminale-d-svt-3-s2-l4', 'La contraction musculaire', 'Phénomènes moléculaires, électriques, mécaniques et énergétiques de la contraction.', 'terminale-d-svt-3', 'terminale-d-svt-3-s2', 8),
('terminale-d-svt-4-s1-l1', 'Le soi, le non-soi et le système immunitaire', 'Notions de soi et de non-soi et présentation du système immunitaire.', 'terminale-d-svt-4', 'terminale-d-svt-4-s1', 1),
('terminale-d-svt-4-s1-l2', 'La réponse immunitaire', 'Réponse immunitaire innée ou non spécifique et réponse acquise ou adaptative.', 'terminale-d-svt-4', 'terminale-d-svt-4-s1', 2),
('terminale-d-svt-4-s1-l3', 'Allergies et maladies auto-immunes', 'Dysfonctionnements du système immunitaire : réactions allergiques et auto-immunes.', 'terminale-d-svt-4', 'terminale-d-svt-4-s1', 3),
('terminale-d-svt-4-s1-l4', 'Domaines d''application de l''immunologie', 'Tests de grossesse, groupes sanguins, transfusion, dépistages, vaccins et sérums.', 'terminale-d-svt-4', 'terminale-d-svt-4-s1', 4),
('terminale-d-svt-4-s2-l1', 'Milieu intérieur et homéostasie', 'Composants et caractéristiques du milieu intérieur et notion d''homéostasie.', 'terminale-d-svt-4', 'terminale-d-svt-4-s2', 5),
('terminale-d-svt-4-s2-l2', 'Le fonctionnement des reins', 'Fonctionnement des reins dans la régulation du milieu intérieur.', 'terminale-d-svt-4', 'terminale-d-svt-4-s2', 6),
('terminale-d-svt-4-s2-l3', 'Régulation hydrominérale et acido-basique', 'Mécanismes de régulation de l''équilibre hydrominéral et de l''équilibre acido-basique par les reins.', 'terminale-d-svt-4', 'terminale-d-svt-4-s2', 7),
('terminale-d-svt-4-s2-l4', 'La régulation de la glycémie', 'Rôles du foie, du pancréas et de la glande thyroïde dans la régulation de la glycémie.', 'terminale-d-svt-4', 'terminale-d-svt-4-s2', 8),
('terminale-d-svt-4-s2-l5', 'Insuffisances rénales et diabète', 'Causes des insuffisances rénales, types de diabète et mesures de lutte.', 'terminale-d-svt-4', 'terminale-d-svt-4-s2', 9),
('terminale-d-svt-4-s3-l1', 'Structure des tissus cardiaques', 'Le tissu musculaire cardiaque ou myocarde et le tissu nodal.', 'terminale-d-svt-4', 'terminale-d-svt-4-s3', 10),
('terminale-d-svt-4-s3-l2', 'Le fonctionnement du cœur', 'Automatisme cardiaque et action du système nerveux et de substances chimiques sur le cœur.', 'terminale-d-svt-4', 'terminale-d-svt-4-s3', 11),
('terminale-d-svt-4-s3-l3', 'La régulation de la pression artérielle', 'Régulation nerveuse et régulation hormonale de la pression artérielle.', 'terminale-d-svt-4', 'terminale-d-svt-4-s3', 12),
('terminale-d-svt-4-s3-l4', 'Prévention de l''hypertension et de l''hypotension', 'Mesures de prévention de l''hypertension et de l''hypotension artérielles.', 'terminale-d-svt-4', 'terminale-d-svt-4-s3', 13)
) as v(slug,title,summary,chapter_slug,subchapter_slug,sort_order)
join chapters c on c.slug=v.chapter_slug
join subchapters sc on sc.slug=v.subchapter_slug
on conflict (slug) do nothing;

insert into activities (lesson_id, type, title, video_provider, sort_order)
select l.id, 'video', 'Vidéo (à venir)', 'placeholder', 0 from lessons l join chapters c on c.id=l.chapter_id
where c.slug in (
  'premiere-c-svt-1',
  'premiere-c-svt-2',
  'premiere-c-svt-3',
  'premiere-d-svt-1',
  'premiere-d-svt-2',
  'premiere-d-svt-3',
  'premiere-d-svt-4',
  'premiere-svt-1',
  'premiere-svt-2',
  'premiere-svt-3',
  'seconde-c-svt-1',
  'seconde-c-svt-2',
  'seconde-c-svt-3',
  'seconde-svt-1',
  'seconde-svt-2',
  'terminale-c-svt-1',
  'terminale-c-svt-2',
  'terminale-c-svt-3',
  'terminale-c-svt-4',
  'terminale-d-svt-1',
  'terminale-d-svt-2',
  'terminale-d-svt-3',
  'terminale-d-svt-4',
  'terminale-svt-1',
  'terminale-svt-2',
  'terminale-svt-3'
)
and not exists (select 1 from activities a where a.lesson_id=l.id and a.type='video');
