-- 0032 : Anglais. Matiere 'anglais', niveau 'certifications' + classe 'toefl'.
-- Placeholders : anglais primaire par chansons (CP1-CM2) et preparation TOEFL.
-- College/lycee scaffolde depuis les syllabi officiels (a venir). Idempotent.

insert into subjects (key, name, icon, description) values
  ('anglais', 'Anglais', '🗣️', 'Anglais du primaire au lycée, et préparation au TOEFL.')
on conflict (key) do nothing;

insert into education_levels (slug, name, description, sort_order) values
  ('certifications', 'Préparation aux examens', 'Certifications d''anglais et concours : ouvrez-vous au monde.', 4)
on conflict (slug) do nothing;

insert into classes (slug, name, level_slug, sort_order, track) values
  ('toefl', 'Préparation TOEFL', 'certifications', 1, 'general')
on conflict (slug) do nothing;

insert into chapters (slug, title, class_slug, subject_key, sort_order) values
('cp1-anglais-1', 'L''alphabet (The Alphabet)', 'cp1', 'anglais', 1),
('cp1-anglais-2', 'Les nombres 1 à 10 (Numbers)', 'cp1', 'anglais', 2),
('cp1-anglais-3', 'Les couleurs (Colours)', 'cp1', 'anglais', 3),
('cp1-anglais-4', 'Bonjour et au revoir (Greetings)', 'cp1', 'anglais', 4),
('cp1-anglais-5', 'Ma famille (My Family)', 'cp1', 'anglais', 5),
('cp2-anglais-1', 'Les nombres 11 à 20 (Numbers)', 'cp2', 'anglais', 1),
('cp2-anglais-2', 'Les animaux (Animals)', 'cp2', 'anglais', 2),
('cp2-anglais-3', 'Le corps (Body Parts)', 'cp2', 'anglais', 3),
('cp2-anglais-4', 'Les fruits (Fruits)', 'cp2', 'anglais', 4),
('cp2-anglais-5', 'Les jours de la semaine (Days of the Week)', 'cp2', 'anglais', 5),
('ce1-anglais-1', 'Le temps qu''il fait (Weather)', 'ce1', 'anglais', 1),
('ce1-anglais-2', 'Les vêtements (Clothes)', 'ce1', 'anglais', 2),
('ce1-anglais-3', 'Les aliments (Food and Drinks)', 'ce1', 'anglais', 3),
('ce1-anglais-4', 'Les actions (Action Verbs)', 'ce1', 'anglais', 4),
('ce1-anglais-5', 'En classe (In the Classroom)', 'ce1', 'anglais', 5),
('ce2-anglais-1', 'Ma maison (My House)', 'ce2', 'anglais', 1),
('ce2-anglais-2', 'Les métiers (Jobs)', 'ce2', 'anglais', 2),
('ce2-anglais-3', 'Les transports (Transport)', 'ce2', 'anglais', 3),
('ce2-anglais-4', 'Les émotions (Feelings)', 'ce2', 'anglais', 4),
('ce2-anglais-5', 'Les mois et les saisons (Months and Seasons)', 'ce2', 'anglais', 5),
('cm1-anglais-1', 'L''heure (Telling the Time)', 'cm1', 'anglais', 1),
('cm1-anglais-2', 'Les loisirs (Hobbies)', 'cm1', 'anglais', 2),
('cm1-anglais-3', 'Les sports (Sports)', 'cm1', 'anglais', 3),
('cm1-anglais-4', 'La nature (Nature)', 'cm1', 'anglais', 4),
('cm1-anglais-5', 'Les achats (Shopping)', 'cm1', 'anglais', 5),
('cm2-anglais-1', 'Demander son chemin (Directions)', 'cm2', 'anglais', 1),
('cm2-anglais-2', 'La routine quotidienne (Daily Routine)', 'cm2', 'anglais', 2),
('cm2-anglais-3', 'Pays et nationalités (Countries and Nationalities)', 'cm2', 'anglais', 3),
('cm2-anglais-4', 'Les fêtes (Holidays)', 'cm2', 'anglais', 4),
('cm2-anglais-5', 'Petites conversations (Simple Conversations)', 'cm2', 'anglais', 5),
('toefl-anglais-1', 'TOEFL Reading (Compréhension écrite)', 'toefl', 'anglais', 1),
('toefl-anglais-2', 'TOEFL Listening (Compréhension orale)', 'toefl', 'anglais', 2),
('toefl-anglais-3', 'TOEFL Speaking (Expression orale)', 'toefl', 'anglais', 3),
('toefl-anglais-4', 'TOEFL Writing (Expression écrite)', 'toefl', 'anglais', 4),
('toefl-anglais-5', 'Grammaire et vocabulaire (Grammar & Vocabulary)', 'toefl', 'anglais', 5),
('toefl-anglais-6', 'Tests blancs (Practice Tests)', 'toefl', 'anglais', 6)
on conflict (slug) do nothing;

insert into subchapters (slug, title, chapter_id, sort_order)
select v.slug, v.title, c.id, v.sort_order from (values
('cp1-anglais-1-s1', 'Chansons et vocabulaire', 'cp1-anglais-1', 1),
('cp1-anglais-2-s1', 'Chansons et vocabulaire', 'cp1-anglais-2', 1),
('cp1-anglais-3-s1', 'Chansons et vocabulaire', 'cp1-anglais-3', 1),
('cp1-anglais-4-s1', 'Chansons et vocabulaire', 'cp1-anglais-4', 1),
('cp1-anglais-5-s1', 'Chansons et vocabulaire', 'cp1-anglais-5', 1),
('cp2-anglais-1-s1', 'Chansons et vocabulaire', 'cp2-anglais-1', 1),
('cp2-anglais-2-s1', 'Chansons et vocabulaire', 'cp2-anglais-2', 1),
('cp2-anglais-3-s1', 'Chansons et vocabulaire', 'cp2-anglais-3', 1),
('cp2-anglais-4-s1', 'Chansons et vocabulaire', 'cp2-anglais-4', 1),
('cp2-anglais-5-s1', 'Chansons et vocabulaire', 'cp2-anglais-5', 1),
('ce1-anglais-1-s1', 'Chansons et vocabulaire', 'ce1-anglais-1', 1),
('ce1-anglais-2-s1', 'Chansons et vocabulaire', 'ce1-anglais-2', 1),
('ce1-anglais-3-s1', 'Chansons et vocabulaire', 'ce1-anglais-3', 1),
('ce1-anglais-4-s1', 'Chansons et vocabulaire', 'ce1-anglais-4', 1),
('ce1-anglais-5-s1', 'Chansons et vocabulaire', 'ce1-anglais-5', 1),
('ce2-anglais-1-s1', 'Chansons et vocabulaire', 'ce2-anglais-1', 1),
('ce2-anglais-2-s1', 'Chansons et vocabulaire', 'ce2-anglais-2', 1),
('ce2-anglais-3-s1', 'Chansons et vocabulaire', 'ce2-anglais-3', 1),
('ce2-anglais-4-s1', 'Chansons et vocabulaire', 'ce2-anglais-4', 1),
('ce2-anglais-5-s1', 'Chansons et vocabulaire', 'ce2-anglais-5', 1),
('cm1-anglais-1-s1', 'Chansons et vocabulaire', 'cm1-anglais-1', 1),
('cm1-anglais-2-s1', 'Chansons et vocabulaire', 'cm1-anglais-2', 1),
('cm1-anglais-3-s1', 'Chansons et vocabulaire', 'cm1-anglais-3', 1),
('cm1-anglais-4-s1', 'Chansons et vocabulaire', 'cm1-anglais-4', 1),
('cm1-anglais-5-s1', 'Chansons et vocabulaire', 'cm1-anglais-5', 1),
('cm2-anglais-1-s1', 'Chansons et vocabulaire', 'cm2-anglais-1', 1),
('cm2-anglais-2-s1', 'Chansons et vocabulaire', 'cm2-anglais-2', 1),
('cm2-anglais-3-s1', 'Chansons et vocabulaire', 'cm2-anglais-3', 1),
('cm2-anglais-4-s1', 'Chansons et vocabulaire', 'cm2-anglais-4', 1),
('cm2-anglais-5-s1', 'Chansons et vocabulaire', 'cm2-anglais-5', 1),
('toefl-anglais-1-s1', 'Stratégies de lecture', 'toefl-anglais-1', 1),
('toefl-anglais-2-s1', 'Écoute active', 'toefl-anglais-2', 1),
('toefl-anglais-3-s1', 'Parler avec aisance', 'toefl-anglais-3', 1),
('toefl-anglais-4-s1', 'Rédiger efficacement', 'toefl-anglais-4', 1),
('toefl-anglais-5-s1', 'Des bases solides', 'toefl-anglais-5', 1),
('toefl-anglais-6-s1', 'S''entraîner en conditions réelles', 'toefl-anglais-6', 1)
) as v(slug,title,chapter_slug,sort_order)
join chapters c on c.slug=v.chapter_slug
on conflict (slug) do nothing;

insert into lessons (slug, title, summary, chapter_id, subchapter_id, sort_order, status, is_free_preview)
select v.slug, v.title, v.summary, c.id, sc.id, v.sort_order, 'draft', false from (values
('cp1-anglais-1-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cp1-anglais-1', 'cp1-anglais-1-s1', 1),
('cp1-anglais-1-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cp1-anglais-1', 'cp1-anglais-1-s1', 2),
('cp1-anglais-2-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cp1-anglais-2', 'cp1-anglais-2-s1', 1),
('cp1-anglais-2-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cp1-anglais-2', 'cp1-anglais-2-s1', 2),
('cp1-anglais-3-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cp1-anglais-3', 'cp1-anglais-3-s1', 1),
('cp1-anglais-3-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cp1-anglais-3', 'cp1-anglais-3-s1', 2),
('cp1-anglais-4-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cp1-anglais-4', 'cp1-anglais-4-s1', 1),
('cp1-anglais-4-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cp1-anglais-4', 'cp1-anglais-4-s1', 2),
('cp1-anglais-5-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cp1-anglais-5', 'cp1-anglais-5-s1', 1),
('cp1-anglais-5-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cp1-anglais-5', 'cp1-anglais-5-s1', 2),
('cp2-anglais-1-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cp2-anglais-1', 'cp2-anglais-1-s1', 1),
('cp2-anglais-1-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cp2-anglais-1', 'cp2-anglais-1-s1', 2),
('cp2-anglais-2-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cp2-anglais-2', 'cp2-anglais-2-s1', 1),
('cp2-anglais-2-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cp2-anglais-2', 'cp2-anglais-2-s1', 2),
('cp2-anglais-3-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cp2-anglais-3', 'cp2-anglais-3-s1', 1),
('cp2-anglais-3-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cp2-anglais-3', 'cp2-anglais-3-s1', 2),
('cp2-anglais-4-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cp2-anglais-4', 'cp2-anglais-4-s1', 1),
('cp2-anglais-4-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cp2-anglais-4', 'cp2-anglais-4-s1', 2),
('cp2-anglais-5-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cp2-anglais-5', 'cp2-anglais-5-s1', 1),
('cp2-anglais-5-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cp2-anglais-5', 'cp2-anglais-5-s1', 2),
('ce1-anglais-1-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'ce1-anglais-1', 'ce1-anglais-1-s1', 1),
('ce1-anglais-1-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'ce1-anglais-1', 'ce1-anglais-1-s1', 2),
('ce1-anglais-2-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'ce1-anglais-2', 'ce1-anglais-2-s1', 1),
('ce1-anglais-2-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'ce1-anglais-2', 'ce1-anglais-2-s1', 2),
('ce1-anglais-3-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'ce1-anglais-3', 'ce1-anglais-3-s1', 1),
('ce1-anglais-3-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'ce1-anglais-3', 'ce1-anglais-3-s1', 2),
('ce1-anglais-4-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'ce1-anglais-4', 'ce1-anglais-4-s1', 1),
('ce1-anglais-4-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'ce1-anglais-4', 'ce1-anglais-4-s1', 2),
('ce1-anglais-5-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'ce1-anglais-5', 'ce1-anglais-5-s1', 1),
('ce1-anglais-5-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'ce1-anglais-5', 'ce1-anglais-5-s1', 2),
('ce2-anglais-1-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'ce2-anglais-1', 'ce2-anglais-1-s1', 1),
('ce2-anglais-1-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'ce2-anglais-1', 'ce2-anglais-1-s1', 2),
('ce2-anglais-2-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'ce2-anglais-2', 'ce2-anglais-2-s1', 1),
('ce2-anglais-2-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'ce2-anglais-2', 'ce2-anglais-2-s1', 2),
('ce2-anglais-3-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'ce2-anglais-3', 'ce2-anglais-3-s1', 1),
('ce2-anglais-3-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'ce2-anglais-3', 'ce2-anglais-3-s1', 2),
('ce2-anglais-4-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'ce2-anglais-4', 'ce2-anglais-4-s1', 1),
('ce2-anglais-4-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'ce2-anglais-4', 'ce2-anglais-4-s1', 2),
('ce2-anglais-5-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'ce2-anglais-5', 'ce2-anglais-5-s1', 1),
('ce2-anglais-5-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'ce2-anglais-5', 'ce2-anglais-5-s1', 2),
('cm1-anglais-1-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cm1-anglais-1', 'cm1-anglais-1-s1', 1),
('cm1-anglais-1-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cm1-anglais-1', 'cm1-anglais-1-s1', 2),
('cm1-anglais-2-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cm1-anglais-2', 'cm1-anglais-2-s1', 1),
('cm1-anglais-2-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cm1-anglais-2', 'cm1-anglais-2-s1', 2),
('cm1-anglais-3-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cm1-anglais-3', 'cm1-anglais-3-s1', 1),
('cm1-anglais-3-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cm1-anglais-3', 'cm1-anglais-3-s1', 2),
('cm1-anglais-4-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cm1-anglais-4', 'cm1-anglais-4-s1', 1),
('cm1-anglais-4-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cm1-anglais-4', 'cm1-anglais-4-s1', 2),
('cm1-anglais-5-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cm1-anglais-5', 'cm1-anglais-5-s1', 1),
('cm1-anglais-5-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cm1-anglais-5', 'cm1-anglais-5-s1', 2),
('cm2-anglais-1-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cm2-anglais-1', 'cm2-anglais-1-s1', 1),
('cm2-anglais-1-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cm2-anglais-1', 'cm2-anglais-1-s1', 2),
('cm2-anglais-2-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cm2-anglais-2', 'cm2-anglais-2-s1', 1),
('cm2-anglais-2-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cm2-anglais-2', 'cm2-anglais-2-s1', 2),
('cm2-anglais-3-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cm2-anglais-3', 'cm2-anglais-3-s1', 1),
('cm2-anglais-3-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cm2-anglais-3', 'cm2-anglais-3-s1', 2),
('cm2-anglais-4-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cm2-anglais-4', 'cm2-anglais-4-s1', 1),
('cm2-anglais-4-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cm2-anglais-4', 'cm2-anglais-4-s1', 2),
('cm2-anglais-5-l1', 'La chanson', 'Apprendre le vocabulaire du thème en chantant.', 'cm2-anglais-5', 'cm2-anglais-5-s1', 1),
('cm2-anglais-5-l2', 'Vocabulaire et jeu', 'Revoir les mots-clés avec des images et un petit jeu.', 'cm2-anglais-5', 'cm2-anglais-5-s1', 2),
('toefl-anglais-1-l1', 'Comprendre le format Reading', 'Structure de la section, types de passages et de questions.', 'toefl-anglais-1', 'toefl-anglais-1-s1', 1),
('toefl-anglais-1-l2', 'Skimming et scanning', 'Repérer l''idée générale et les informations précises rapidement.', 'toefl-anglais-1', 'toefl-anglais-1-s1', 2),
('toefl-anglais-1-l3', 'Vocabulaire en contexte', 'Deviner le sens d''un mot grâce au contexte.', 'toefl-anglais-1', 'toefl-anglais-1-s1', 3),
('toefl-anglais-1-l4', 'Idée principale et détails', 'Distinguer l''essentiel des détails d''appui.', 'toefl-anglais-1', 'toefl-anglais-1-s1', 4),
('toefl-anglais-1-l5', 'Questions d''inférence', 'Déduire ce qui n''est pas dit explicitement.', 'toefl-anglais-1', 'toefl-anglais-1-s1', 5),
('toefl-anglais-2-l1', 'Comprendre le format Listening', 'Cours magistraux et conversations : ce qui est évalué.', 'toefl-anglais-2', 'toefl-anglais-2-s1', 1),
('toefl-anglais-2-l2', 'Cours magistraux (lectures)', 'Suivre un exposé académique et sa structure.', 'toefl-anglais-2', 'toefl-anglais-2-s1', 2),
('toefl-anglais-2-l3', 'Conversations', 'Comprendre un échange sur un campus.', 'toefl-anglais-2', 'toefl-anglais-2-s1', 3),
('toefl-anglais-2-l4', 'Prise de notes efficace', 'Noter l''essentiel pendant l''écoute.', 'toefl-anglais-2', 'toefl-anglais-2-s1', 4),
('toefl-anglais-2-l5', 'Questions d''attitude et d''organisation', 'Répondre aux questions sur le ton et le plan.', 'toefl-anglais-2', 'toefl-anglais-2-s1', 5),
('toefl-anglais-3-l1', 'Comprendre le format Speaking', 'Tâches indépendantes et intégrées, barème.', 'toefl-anglais-3', 'toefl-anglais-3-s1', 1),
('toefl-anglais-3-l2', 'Tâche indépendante', 'Donner et justifier son opinion en 45 secondes.', 'toefl-anglais-3', 'toefl-anglais-3-s1', 2),
('toefl-anglais-3-l3', 'Tâches intégrées', 'Combiner lecture, écoute et parole.', 'toefl-anglais-3', 'toefl-anglais-3-s1', 3),
('toefl-anglais-3-l4', 'Prononciation et fluidité', 'Améliorer la clarté, le rythme et l''intonation.', 'toefl-anglais-3', 'toefl-anglais-3-s1', 4),
('toefl-anglais-3-l5', 'Gérer le temps de réponse', 'Structurer sa réponse dans le temps imparti.', 'toefl-anglais-3', 'toefl-anglais-3-s1', 5),
('toefl-anglais-4-l1', 'Comprendre le format Writing', 'Integrated et Independent : attentes et barème.', 'toefl-anglais-4', 'toefl-anglais-4-s1', 1),
('toefl-anglais-4-l2', 'Integrated Writing', 'Résumer et relier lecture et écoute.', 'toefl-anglais-4', 'toefl-anglais-4-s1', 2),
('toefl-anglais-4-l3', 'Independent Essay', 'Construire un essai argumenté.', 'toefl-anglais-4', 'toefl-anglais-4-s1', 3),
('toefl-anglais-4-l4', 'Structure et connecteurs', 'Organiser ses idées avec des mots de liaison.', 'toefl-anglais-4', 'toefl-anglais-4-s1', 4),
('toefl-anglais-4-l5', 'Grammaire pour l''écrit', 'Éviter les erreurs qui coûtent des points.', 'toefl-anglais-4', 'toefl-anglais-4-s1', 5),
('toefl-anglais-5-l1', 'Temps verbaux essentiels', 'Présent, passé, futur et temps composés.', 'toefl-anglais-5', 'toefl-anglais-5-s1', 1),
('toefl-anglais-5-l2', 'Structures de phrases clés', 'Relatives, conditionnelles, voix passive.', 'toefl-anglais-5', 'toefl-anglais-5-s1', 2),
('toefl-anglais-5-l3', 'Vocabulaire académique', 'Les mots fréquents des textes TOEFL.', 'toefl-anglais-5', 'toefl-anglais-5-s1', 3),
('toefl-anglais-5-l4', 'Erreurs fréquentes à éviter', 'Faux-amis et pièges classiques.', 'toefl-anglais-5', 'toefl-anglais-5-s1', 4),
('toefl-anglais-6-l1', 'Test blanc 1', 'Examen complet chronométré.', 'toefl-anglais-6', 'toefl-anglais-6-s1', 1),
('toefl-anglais-6-l2', 'Test blanc 2', 'Deuxième examen complet.', 'toefl-anglais-6', 'toefl-anglais-6-s1', 2),
('toefl-anglais-6-l3', 'Test blanc 3', 'Troisième examen complet.', 'toefl-anglais-6', 'toefl-anglais-6-s1', 3),
('toefl-anglais-6-l4', 'Analyser ses résultats', 'Identifier ses points faibles et progresser.', 'toefl-anglais-6', 'toefl-anglais-6-s1', 4)
) as v(slug,title,summary,chapter_slug,subchapter_slug,sort_order)
join chapters c on c.slug=v.chapter_slug
join subchapters sc on sc.slug=v.subchapter_slug
on conflict (slug) do nothing;

insert into activities (lesson_id, type, title, video_provider, sort_order)
select l.id, 'video', 'Vidéo (à venir)', 'placeholder', 0 from lessons l join chapters c on c.id=l.chapter_id
where c.slug in (
  'ce1-anglais-1',
  'ce1-anglais-2',
  'ce1-anglais-3',
  'ce1-anglais-4',
  'ce1-anglais-5',
  'ce2-anglais-1',
  'ce2-anglais-2',
  'ce2-anglais-3',
  'ce2-anglais-4',
  'ce2-anglais-5',
  'cm1-anglais-1',
  'cm1-anglais-2',
  'cm1-anglais-3',
  'cm1-anglais-4',
  'cm1-anglais-5',
  'cm2-anglais-1',
  'cm2-anglais-2',
  'cm2-anglais-3',
  'cm2-anglais-4',
  'cm2-anglais-5',
  'cp1-anglais-1',
  'cp1-anglais-2',
  'cp1-anglais-3',
  'cp1-anglais-4',
  'cp1-anglais-5',
  'cp2-anglais-1',
  'cp2-anglais-2',
  'cp2-anglais-3',
  'cp2-anglais-4',
  'cp2-anglais-5',
  'toefl-anglais-1',
  'toefl-anglais-2',
  'toefl-anglais-3',
  'toefl-anglais-4',
  'toefl-anglais-5',
  'toefl-anglais-6'
)
and not exists (select 1 from activities a where a.lesson_id=l.id and a.type='video');
