-- 0035 : kits de preparation aux examens nationaux (series scientifiques).
-- CEPD, BEPC, Probatoire C/D, Baccalaureat C/D. Chaque examen = une classe
-- sous le niveau 'certifications', avec sa formule annuelle dediee (comme
-- le TOEFL). Contenu = problem-solving (methodo, annales corrigees, epreuves
-- blanches) par matiere. Series litteraires (A) a venir avec Francais/Philo.
-- Idempotent.

insert into classes (slug, name, level_slug, sort_order, track) values
('cepd', 'CEPD', 'certifications', 1, 'general'),
('bepc', 'BEPC', 'certifications', 2, 'general'),
('probatoire-c', 'Probatoire C', 'certifications', 3, 'general'),
('probatoire-d', 'Probatoire D', 'certifications', 4, 'general'),
('bac-c', 'Baccalauréat C', 'certifications', 5, 'general'),
('bac-d', 'Baccalauréat D', 'certifications', 6, 'general')
on conflict (slug) do nothing;

update classes set sort_order = 7 where slug = 'toefl';

insert into plans (slug, name, price_xof, cadence, scope) values
('cepd-annuel', 'Préparation CEPD', 8000, 'annual', 'class'),
('bepc-annuel', 'Préparation BEPC', 8000, 'annual', 'class'),
('probatoire-c-annuel', 'Préparation Probatoire C', 8000, 'annual', 'class'),
('probatoire-d-annuel', 'Préparation Probatoire D', 8000, 'annual', 'class'),
('bac-c-annuel', 'Préparation Baccalauréat C', 8000, 'annual', 'class'),
('bac-d-annuel', 'Préparation Baccalauréat D', 8000, 'annual', 'class')
on conflict (slug) do update set name=excluded.name, price_xof=excluded.price_xof, cadence=excluded.cadence, scope=excluded.scope, is_active=true;

insert into chapters (slug, title, class_slug, subject_key, sort_order) values
('cepd-mathematiques-1', 'Méthodologie de l''épreuve', 'cepd', 'mathematiques', 1),
('cepd-mathematiques-2', 'Annales corrigées', 'cepd', 'mathematiques', 2),
('cepd-mathematiques-3', 'Épreuves blanches', 'cepd', 'mathematiques', 3),
('bepc-mathematiques-1', 'Méthodologie de l''épreuve', 'bepc', 'mathematiques', 1),
('bepc-mathematiques-2', 'Annales corrigées', 'bepc', 'mathematiques', 2),
('bepc-mathematiques-3', 'Épreuves blanches', 'bepc', 'mathematiques', 3),
('bepc-spt-1', 'Méthodologie de l''épreuve', 'bepc', 'spt', 1),
('bepc-spt-2', 'Annales corrigées', 'bepc', 'spt', 2),
('bepc-spt-3', 'Épreuves blanches', 'bepc', 'spt', 3),
('bepc-svt-1', 'Méthodologie de l''épreuve', 'bepc', 'svt', 1),
('bepc-svt-2', 'Annales corrigées', 'bepc', 'svt', 2),
('bepc-svt-3', 'Épreuves blanches', 'bepc', 'svt', 3),
('probatoire-c-mathematiques-1', 'Méthodologie de l''épreuve', 'probatoire-c', 'mathematiques', 1),
('probatoire-c-mathematiques-2', 'Annales corrigées', 'probatoire-c', 'mathematiques', 2),
('probatoire-c-mathematiques-3', 'Épreuves blanches', 'probatoire-c', 'mathematiques', 3),
('probatoire-c-physique-1', 'Méthodologie de l''épreuve', 'probatoire-c', 'physique', 1),
('probatoire-c-physique-2', 'Annales corrigées', 'probatoire-c', 'physique', 2),
('probatoire-c-physique-3', 'Épreuves blanches', 'probatoire-c', 'physique', 3),
('probatoire-c-chimie-1', 'Méthodologie de l''épreuve', 'probatoire-c', 'chimie', 1),
('probatoire-c-chimie-2', 'Annales corrigées', 'probatoire-c', 'chimie', 2),
('probatoire-c-chimie-3', 'Épreuves blanches', 'probatoire-c', 'chimie', 3),
('probatoire-c-svt-1', 'Méthodologie de l''épreuve', 'probatoire-c', 'svt', 1),
('probatoire-c-svt-2', 'Annales corrigées', 'probatoire-c', 'svt', 2),
('probatoire-c-svt-3', 'Épreuves blanches', 'probatoire-c', 'svt', 3),
('probatoire-d-mathematiques-1', 'Méthodologie de l''épreuve', 'probatoire-d', 'mathematiques', 1),
('probatoire-d-mathematiques-2', 'Annales corrigées', 'probatoire-d', 'mathematiques', 2),
('probatoire-d-mathematiques-3', 'Épreuves blanches', 'probatoire-d', 'mathematiques', 3),
('probatoire-d-physique-1', 'Méthodologie de l''épreuve', 'probatoire-d', 'physique', 1),
('probatoire-d-physique-2', 'Annales corrigées', 'probatoire-d', 'physique', 2),
('probatoire-d-physique-3', 'Épreuves blanches', 'probatoire-d', 'physique', 3),
('probatoire-d-chimie-1', 'Méthodologie de l''épreuve', 'probatoire-d', 'chimie', 1),
('probatoire-d-chimie-2', 'Annales corrigées', 'probatoire-d', 'chimie', 2),
('probatoire-d-chimie-3', 'Épreuves blanches', 'probatoire-d', 'chimie', 3),
('probatoire-d-svt-1', 'Méthodologie de l''épreuve', 'probatoire-d', 'svt', 1),
('probatoire-d-svt-2', 'Annales corrigées', 'probatoire-d', 'svt', 2),
('probatoire-d-svt-3', 'Épreuves blanches', 'probatoire-d', 'svt', 3),
('bac-c-mathematiques-1', 'Méthodologie de l''épreuve', 'bac-c', 'mathematiques', 1),
('bac-c-mathematiques-2', 'Annales corrigées', 'bac-c', 'mathematiques', 2),
('bac-c-mathematiques-3', 'Épreuves blanches', 'bac-c', 'mathematiques', 3),
('bac-c-physique-1', 'Méthodologie de l''épreuve', 'bac-c', 'physique', 1),
('bac-c-physique-2', 'Annales corrigées', 'bac-c', 'physique', 2),
('bac-c-physique-3', 'Épreuves blanches', 'bac-c', 'physique', 3),
('bac-c-chimie-1', 'Méthodologie de l''épreuve', 'bac-c', 'chimie', 1),
('bac-c-chimie-2', 'Annales corrigées', 'bac-c', 'chimie', 2),
('bac-c-chimie-3', 'Épreuves blanches', 'bac-c', 'chimie', 3),
('bac-c-svt-1', 'Méthodologie de l''épreuve', 'bac-c', 'svt', 1),
('bac-c-svt-2', 'Annales corrigées', 'bac-c', 'svt', 2),
('bac-c-svt-3', 'Épreuves blanches', 'bac-c', 'svt', 3),
('bac-d-mathematiques-1', 'Méthodologie de l''épreuve', 'bac-d', 'mathematiques', 1),
('bac-d-mathematiques-2', 'Annales corrigées', 'bac-d', 'mathematiques', 2),
('bac-d-mathematiques-3', 'Épreuves blanches', 'bac-d', 'mathematiques', 3),
('bac-d-physique-1', 'Méthodologie de l''épreuve', 'bac-d', 'physique', 1),
('bac-d-physique-2', 'Annales corrigées', 'bac-d', 'physique', 2),
('bac-d-physique-3', 'Épreuves blanches', 'bac-d', 'physique', 3),
('bac-d-chimie-1', 'Méthodologie de l''épreuve', 'bac-d', 'chimie', 1),
('bac-d-chimie-2', 'Annales corrigées', 'bac-d', 'chimie', 2),
('bac-d-chimie-3', 'Épreuves blanches', 'bac-d', 'chimie', 3),
('bac-d-svt-1', 'Méthodologie de l''épreuve', 'bac-d', 'svt', 1),
('bac-d-svt-2', 'Annales corrigées', 'bac-d', 'svt', 2),
('bac-d-svt-3', 'Épreuves blanches', 'bac-d', 'svt', 3)
on conflict (slug) do nothing;

insert into subchapters (slug, title, chapter_id, sort_order)
select v.slug, v.title, c.id, v.sort_order from (values
('cepd-mathematiques-1-s1', 'Réussir l''épreuve', 'cepd-mathematiques-1', 1),
('cepd-mathematiques-2-s1', 'Sujets des sessions passées', 'cepd-mathematiques-2', 1),
('cepd-mathematiques-3-s1', 'En conditions réelles', 'cepd-mathematiques-3', 1),
('bepc-mathematiques-1-s1', 'Réussir l''épreuve', 'bepc-mathematiques-1', 1),
('bepc-mathematiques-2-s1', 'Sujets des sessions passées', 'bepc-mathematiques-2', 1),
('bepc-mathematiques-3-s1', 'En conditions réelles', 'bepc-mathematiques-3', 1),
('bepc-spt-1-s1', 'Réussir l''épreuve', 'bepc-spt-1', 1),
('bepc-spt-2-s1', 'Sujets des sessions passées', 'bepc-spt-2', 1),
('bepc-spt-3-s1', 'En conditions réelles', 'bepc-spt-3', 1),
('bepc-svt-1-s1', 'Réussir l''épreuve', 'bepc-svt-1', 1),
('bepc-svt-2-s1', 'Sujets des sessions passées', 'bepc-svt-2', 1),
('bepc-svt-3-s1', 'En conditions réelles', 'bepc-svt-3', 1),
('probatoire-c-mathematiques-1-s1', 'Réussir l''épreuve', 'probatoire-c-mathematiques-1', 1),
('probatoire-c-mathematiques-2-s1', 'Sujets des sessions passées', 'probatoire-c-mathematiques-2', 1),
('probatoire-c-mathematiques-3-s1', 'En conditions réelles', 'probatoire-c-mathematiques-3', 1),
('probatoire-c-physique-1-s1', 'Réussir l''épreuve', 'probatoire-c-physique-1', 1),
('probatoire-c-physique-2-s1', 'Sujets des sessions passées', 'probatoire-c-physique-2', 1),
('probatoire-c-physique-3-s1', 'En conditions réelles', 'probatoire-c-physique-3', 1),
('probatoire-c-chimie-1-s1', 'Réussir l''épreuve', 'probatoire-c-chimie-1', 1),
('probatoire-c-chimie-2-s1', 'Sujets des sessions passées', 'probatoire-c-chimie-2', 1),
('probatoire-c-chimie-3-s1', 'En conditions réelles', 'probatoire-c-chimie-3', 1),
('probatoire-c-svt-1-s1', 'Réussir l''épreuve', 'probatoire-c-svt-1', 1),
('probatoire-c-svt-2-s1', 'Sujets des sessions passées', 'probatoire-c-svt-2', 1),
('probatoire-c-svt-3-s1', 'En conditions réelles', 'probatoire-c-svt-3', 1),
('probatoire-d-mathematiques-1-s1', 'Réussir l''épreuve', 'probatoire-d-mathematiques-1', 1),
('probatoire-d-mathematiques-2-s1', 'Sujets des sessions passées', 'probatoire-d-mathematiques-2', 1),
('probatoire-d-mathematiques-3-s1', 'En conditions réelles', 'probatoire-d-mathematiques-3', 1),
('probatoire-d-physique-1-s1', 'Réussir l''épreuve', 'probatoire-d-physique-1', 1),
('probatoire-d-physique-2-s1', 'Sujets des sessions passées', 'probatoire-d-physique-2', 1),
('probatoire-d-physique-3-s1', 'En conditions réelles', 'probatoire-d-physique-3', 1),
('probatoire-d-chimie-1-s1', 'Réussir l''épreuve', 'probatoire-d-chimie-1', 1),
('probatoire-d-chimie-2-s1', 'Sujets des sessions passées', 'probatoire-d-chimie-2', 1),
('probatoire-d-chimie-3-s1', 'En conditions réelles', 'probatoire-d-chimie-3', 1),
('probatoire-d-svt-1-s1', 'Réussir l''épreuve', 'probatoire-d-svt-1', 1),
('probatoire-d-svt-2-s1', 'Sujets des sessions passées', 'probatoire-d-svt-2', 1),
('probatoire-d-svt-3-s1', 'En conditions réelles', 'probatoire-d-svt-3', 1),
('bac-c-mathematiques-1-s1', 'Réussir l''épreuve', 'bac-c-mathematiques-1', 1),
('bac-c-mathematiques-2-s1', 'Sujets des sessions passées', 'bac-c-mathematiques-2', 1),
('bac-c-mathematiques-3-s1', 'En conditions réelles', 'bac-c-mathematiques-3', 1),
('bac-c-physique-1-s1', 'Réussir l''épreuve', 'bac-c-physique-1', 1),
('bac-c-physique-2-s1', 'Sujets des sessions passées', 'bac-c-physique-2', 1),
('bac-c-physique-3-s1', 'En conditions réelles', 'bac-c-physique-3', 1),
('bac-c-chimie-1-s1', 'Réussir l''épreuve', 'bac-c-chimie-1', 1),
('bac-c-chimie-2-s1', 'Sujets des sessions passées', 'bac-c-chimie-2', 1),
('bac-c-chimie-3-s1', 'En conditions réelles', 'bac-c-chimie-3', 1),
('bac-c-svt-1-s1', 'Réussir l''épreuve', 'bac-c-svt-1', 1),
('bac-c-svt-2-s1', 'Sujets des sessions passées', 'bac-c-svt-2', 1),
('bac-c-svt-3-s1', 'En conditions réelles', 'bac-c-svt-3', 1),
('bac-d-mathematiques-1-s1', 'Réussir l''épreuve', 'bac-d-mathematiques-1', 1),
('bac-d-mathematiques-2-s1', 'Sujets des sessions passées', 'bac-d-mathematiques-2', 1),
('bac-d-mathematiques-3-s1', 'En conditions réelles', 'bac-d-mathematiques-3', 1),
('bac-d-physique-1-s1', 'Réussir l''épreuve', 'bac-d-physique-1', 1),
('bac-d-physique-2-s1', 'Sujets des sessions passées', 'bac-d-physique-2', 1),
('bac-d-physique-3-s1', 'En conditions réelles', 'bac-d-physique-3', 1),
('bac-d-chimie-1-s1', 'Réussir l''épreuve', 'bac-d-chimie-1', 1),
('bac-d-chimie-2-s1', 'Sujets des sessions passées', 'bac-d-chimie-2', 1),
('bac-d-chimie-3-s1', 'En conditions réelles', 'bac-d-chimie-3', 1),
('bac-d-svt-1-s1', 'Réussir l''épreuve', 'bac-d-svt-1', 1),
('bac-d-svt-2-s1', 'Sujets des sessions passées', 'bac-d-svt-2', 1),
('bac-d-svt-3-s1', 'En conditions réelles', 'bac-d-svt-3', 1)
) as v(slug,title,chapter_slug,sort_order)
join chapters c on c.slug=v.chapter_slug
on conflict (slug) do nothing;

insert into lessons (slug, title, summary, chapter_id, subchapter_id, sort_order, status, is_free_preview)
select v.slug, v.title, v.summary, c.id, sc.id, v.sort_order, 'draft', false from (values
('cepd-mathematiques-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'cepd-mathematiques-1', 'cepd-mathematiques-1-s1', 1),
('cepd-mathematiques-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'cepd-mathematiques-1', 'cepd-mathematiques-1-s1', 2),
('cepd-mathematiques-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'cepd-mathematiques-1', 'cepd-mathematiques-1-s1', 3),
('cepd-mathematiques-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'cepd-mathematiques-1', 'cepd-mathematiques-1-s1', 4),
('cepd-mathematiques-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'cepd-mathematiques-2', 'cepd-mathematiques-2-s1', 1),
('cepd-mathematiques-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'cepd-mathematiques-2', 'cepd-mathematiques-2-s1', 2),
('cepd-mathematiques-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'cepd-mathematiques-2', 'cepd-mathematiques-2-s1', 3),
('cepd-mathematiques-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'cepd-mathematiques-3', 'cepd-mathematiques-3-s1', 1),
('cepd-mathematiques-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'cepd-mathematiques-3', 'cepd-mathematiques-3-s1', 2),
('bepc-mathematiques-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'bepc-mathematiques-1', 'bepc-mathematiques-1-s1', 1),
('bepc-mathematiques-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'bepc-mathematiques-1', 'bepc-mathematiques-1-s1', 2),
('bepc-mathematiques-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'bepc-mathematiques-1', 'bepc-mathematiques-1-s1', 3),
('bepc-mathematiques-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'bepc-mathematiques-1', 'bepc-mathematiques-1-s1', 4),
('bepc-mathematiques-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'bepc-mathematiques-2', 'bepc-mathematiques-2-s1', 1),
('bepc-mathematiques-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'bepc-mathematiques-2', 'bepc-mathematiques-2-s1', 2),
('bepc-mathematiques-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'bepc-mathematiques-2', 'bepc-mathematiques-2-s1', 3),
('bepc-mathematiques-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'bepc-mathematiques-3', 'bepc-mathematiques-3-s1', 1),
('bepc-mathematiques-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'bepc-mathematiques-3', 'bepc-mathematiques-3-s1', 2),
('bepc-spt-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'bepc-spt-1', 'bepc-spt-1-s1', 1),
('bepc-spt-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'bepc-spt-1', 'bepc-spt-1-s1', 2),
('bepc-spt-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'bepc-spt-1', 'bepc-spt-1-s1', 3),
('bepc-spt-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'bepc-spt-1', 'bepc-spt-1-s1', 4),
('bepc-spt-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'bepc-spt-2', 'bepc-spt-2-s1', 1),
('bepc-spt-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'bepc-spt-2', 'bepc-spt-2-s1', 2),
('bepc-spt-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'bepc-spt-2', 'bepc-spt-2-s1', 3),
('bepc-spt-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'bepc-spt-3', 'bepc-spt-3-s1', 1),
('bepc-spt-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'bepc-spt-3', 'bepc-spt-3-s1', 2),
('bepc-svt-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'bepc-svt-1', 'bepc-svt-1-s1', 1),
('bepc-svt-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'bepc-svt-1', 'bepc-svt-1-s1', 2),
('bepc-svt-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'bepc-svt-1', 'bepc-svt-1-s1', 3),
('bepc-svt-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'bepc-svt-1', 'bepc-svt-1-s1', 4),
('bepc-svt-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'bepc-svt-2', 'bepc-svt-2-s1', 1),
('bepc-svt-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'bepc-svt-2', 'bepc-svt-2-s1', 2),
('bepc-svt-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'bepc-svt-2', 'bepc-svt-2-s1', 3),
('bepc-svt-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'bepc-svt-3', 'bepc-svt-3-s1', 1),
('bepc-svt-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'bepc-svt-3', 'bepc-svt-3-s1', 2),
('probatoire-c-mathematiques-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'probatoire-c-mathematiques-1', 'probatoire-c-mathematiques-1-s1', 1),
('probatoire-c-mathematiques-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'probatoire-c-mathematiques-1', 'probatoire-c-mathematiques-1-s1', 2),
('probatoire-c-mathematiques-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'probatoire-c-mathematiques-1', 'probatoire-c-mathematiques-1-s1', 3),
('probatoire-c-mathematiques-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'probatoire-c-mathematiques-1', 'probatoire-c-mathematiques-1-s1', 4),
('probatoire-c-mathematiques-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'probatoire-c-mathematiques-2', 'probatoire-c-mathematiques-2-s1', 1),
('probatoire-c-mathematiques-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'probatoire-c-mathematiques-2', 'probatoire-c-mathematiques-2-s1', 2),
('probatoire-c-mathematiques-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'probatoire-c-mathematiques-2', 'probatoire-c-mathematiques-2-s1', 3),
('probatoire-c-mathematiques-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'probatoire-c-mathematiques-3', 'probatoire-c-mathematiques-3-s1', 1),
('probatoire-c-mathematiques-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'probatoire-c-mathematiques-3', 'probatoire-c-mathematiques-3-s1', 2),
('probatoire-c-physique-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'probatoire-c-physique-1', 'probatoire-c-physique-1-s1', 1),
('probatoire-c-physique-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'probatoire-c-physique-1', 'probatoire-c-physique-1-s1', 2),
('probatoire-c-physique-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'probatoire-c-physique-1', 'probatoire-c-physique-1-s1', 3),
('probatoire-c-physique-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'probatoire-c-physique-1', 'probatoire-c-physique-1-s1', 4),
('probatoire-c-physique-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'probatoire-c-physique-2', 'probatoire-c-physique-2-s1', 1),
('probatoire-c-physique-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'probatoire-c-physique-2', 'probatoire-c-physique-2-s1', 2),
('probatoire-c-physique-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'probatoire-c-physique-2', 'probatoire-c-physique-2-s1', 3),
('probatoire-c-physique-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'probatoire-c-physique-3', 'probatoire-c-physique-3-s1', 1),
('probatoire-c-physique-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'probatoire-c-physique-3', 'probatoire-c-physique-3-s1', 2),
('probatoire-c-chimie-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'probatoire-c-chimie-1', 'probatoire-c-chimie-1-s1', 1),
('probatoire-c-chimie-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'probatoire-c-chimie-1', 'probatoire-c-chimie-1-s1', 2),
('probatoire-c-chimie-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'probatoire-c-chimie-1', 'probatoire-c-chimie-1-s1', 3),
('probatoire-c-chimie-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'probatoire-c-chimie-1', 'probatoire-c-chimie-1-s1', 4),
('probatoire-c-chimie-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'probatoire-c-chimie-2', 'probatoire-c-chimie-2-s1', 1),
('probatoire-c-chimie-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'probatoire-c-chimie-2', 'probatoire-c-chimie-2-s1', 2),
('probatoire-c-chimie-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'probatoire-c-chimie-2', 'probatoire-c-chimie-2-s1', 3),
('probatoire-c-chimie-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'probatoire-c-chimie-3', 'probatoire-c-chimie-3-s1', 1),
('probatoire-c-chimie-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'probatoire-c-chimie-3', 'probatoire-c-chimie-3-s1', 2),
('probatoire-c-svt-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'probatoire-c-svt-1', 'probatoire-c-svt-1-s1', 1),
('probatoire-c-svt-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'probatoire-c-svt-1', 'probatoire-c-svt-1-s1', 2),
('probatoire-c-svt-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'probatoire-c-svt-1', 'probatoire-c-svt-1-s1', 3),
('probatoire-c-svt-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'probatoire-c-svt-1', 'probatoire-c-svt-1-s1', 4),
('probatoire-c-svt-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'probatoire-c-svt-2', 'probatoire-c-svt-2-s1', 1),
('probatoire-c-svt-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'probatoire-c-svt-2', 'probatoire-c-svt-2-s1', 2),
('probatoire-c-svt-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'probatoire-c-svt-2', 'probatoire-c-svt-2-s1', 3),
('probatoire-c-svt-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'probatoire-c-svt-3', 'probatoire-c-svt-3-s1', 1),
('probatoire-c-svt-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'probatoire-c-svt-3', 'probatoire-c-svt-3-s1', 2),
('probatoire-d-mathematiques-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'probatoire-d-mathematiques-1', 'probatoire-d-mathematiques-1-s1', 1),
('probatoire-d-mathematiques-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'probatoire-d-mathematiques-1', 'probatoire-d-mathematiques-1-s1', 2),
('probatoire-d-mathematiques-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'probatoire-d-mathematiques-1', 'probatoire-d-mathematiques-1-s1', 3),
('probatoire-d-mathematiques-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'probatoire-d-mathematiques-1', 'probatoire-d-mathematiques-1-s1', 4),
('probatoire-d-mathematiques-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'probatoire-d-mathematiques-2', 'probatoire-d-mathematiques-2-s1', 1),
('probatoire-d-mathematiques-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'probatoire-d-mathematiques-2', 'probatoire-d-mathematiques-2-s1', 2),
('probatoire-d-mathematiques-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'probatoire-d-mathematiques-2', 'probatoire-d-mathematiques-2-s1', 3),
('probatoire-d-mathematiques-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'probatoire-d-mathematiques-3', 'probatoire-d-mathematiques-3-s1', 1),
('probatoire-d-mathematiques-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'probatoire-d-mathematiques-3', 'probatoire-d-mathematiques-3-s1', 2),
('probatoire-d-physique-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'probatoire-d-physique-1', 'probatoire-d-physique-1-s1', 1),
('probatoire-d-physique-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'probatoire-d-physique-1', 'probatoire-d-physique-1-s1', 2),
('probatoire-d-physique-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'probatoire-d-physique-1', 'probatoire-d-physique-1-s1', 3),
('probatoire-d-physique-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'probatoire-d-physique-1', 'probatoire-d-physique-1-s1', 4),
('probatoire-d-physique-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'probatoire-d-physique-2', 'probatoire-d-physique-2-s1', 1),
('probatoire-d-physique-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'probatoire-d-physique-2', 'probatoire-d-physique-2-s1', 2),
('probatoire-d-physique-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'probatoire-d-physique-2', 'probatoire-d-physique-2-s1', 3),
('probatoire-d-physique-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'probatoire-d-physique-3', 'probatoire-d-physique-3-s1', 1),
('probatoire-d-physique-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'probatoire-d-physique-3', 'probatoire-d-physique-3-s1', 2),
('probatoire-d-chimie-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'probatoire-d-chimie-1', 'probatoire-d-chimie-1-s1', 1),
('probatoire-d-chimie-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'probatoire-d-chimie-1', 'probatoire-d-chimie-1-s1', 2),
('probatoire-d-chimie-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'probatoire-d-chimie-1', 'probatoire-d-chimie-1-s1', 3),
('probatoire-d-chimie-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'probatoire-d-chimie-1', 'probatoire-d-chimie-1-s1', 4),
('probatoire-d-chimie-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'probatoire-d-chimie-2', 'probatoire-d-chimie-2-s1', 1),
('probatoire-d-chimie-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'probatoire-d-chimie-2', 'probatoire-d-chimie-2-s1', 2),
('probatoire-d-chimie-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'probatoire-d-chimie-2', 'probatoire-d-chimie-2-s1', 3),
('probatoire-d-chimie-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'probatoire-d-chimie-3', 'probatoire-d-chimie-3-s1', 1),
('probatoire-d-chimie-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'probatoire-d-chimie-3', 'probatoire-d-chimie-3-s1', 2),
('probatoire-d-svt-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'probatoire-d-svt-1', 'probatoire-d-svt-1-s1', 1),
('probatoire-d-svt-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'probatoire-d-svt-1', 'probatoire-d-svt-1-s1', 2),
('probatoire-d-svt-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'probatoire-d-svt-1', 'probatoire-d-svt-1-s1', 3),
('probatoire-d-svt-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'probatoire-d-svt-1', 'probatoire-d-svt-1-s1', 4),
('probatoire-d-svt-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'probatoire-d-svt-2', 'probatoire-d-svt-2-s1', 1),
('probatoire-d-svt-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'probatoire-d-svt-2', 'probatoire-d-svt-2-s1', 2),
('probatoire-d-svt-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'probatoire-d-svt-2', 'probatoire-d-svt-2-s1', 3),
('probatoire-d-svt-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'probatoire-d-svt-3', 'probatoire-d-svt-3-s1', 1),
('probatoire-d-svt-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'probatoire-d-svt-3', 'probatoire-d-svt-3-s1', 2),
('bac-c-mathematiques-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'bac-c-mathematiques-1', 'bac-c-mathematiques-1-s1', 1),
('bac-c-mathematiques-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'bac-c-mathematiques-1', 'bac-c-mathematiques-1-s1', 2),
('bac-c-mathematiques-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'bac-c-mathematiques-1', 'bac-c-mathematiques-1-s1', 3),
('bac-c-mathematiques-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'bac-c-mathematiques-1', 'bac-c-mathematiques-1-s1', 4),
('bac-c-mathematiques-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'bac-c-mathematiques-2', 'bac-c-mathematiques-2-s1', 1),
('bac-c-mathematiques-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'bac-c-mathematiques-2', 'bac-c-mathematiques-2-s1', 2),
('bac-c-mathematiques-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'bac-c-mathematiques-2', 'bac-c-mathematiques-2-s1', 3),
('bac-c-mathematiques-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'bac-c-mathematiques-3', 'bac-c-mathematiques-3-s1', 1),
('bac-c-mathematiques-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'bac-c-mathematiques-3', 'bac-c-mathematiques-3-s1', 2),
('bac-c-physique-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'bac-c-physique-1', 'bac-c-physique-1-s1', 1),
('bac-c-physique-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'bac-c-physique-1', 'bac-c-physique-1-s1', 2),
('bac-c-physique-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'bac-c-physique-1', 'bac-c-physique-1-s1', 3),
('bac-c-physique-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'bac-c-physique-1', 'bac-c-physique-1-s1', 4),
('bac-c-physique-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'bac-c-physique-2', 'bac-c-physique-2-s1', 1),
('bac-c-physique-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'bac-c-physique-2', 'bac-c-physique-2-s1', 2),
('bac-c-physique-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'bac-c-physique-2', 'bac-c-physique-2-s1', 3),
('bac-c-physique-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'bac-c-physique-3', 'bac-c-physique-3-s1', 1),
('bac-c-physique-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'bac-c-physique-3', 'bac-c-physique-3-s1', 2),
('bac-c-chimie-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'bac-c-chimie-1', 'bac-c-chimie-1-s1', 1),
('bac-c-chimie-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'bac-c-chimie-1', 'bac-c-chimie-1-s1', 2),
('bac-c-chimie-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'bac-c-chimie-1', 'bac-c-chimie-1-s1', 3),
('bac-c-chimie-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'bac-c-chimie-1', 'bac-c-chimie-1-s1', 4),
('bac-c-chimie-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'bac-c-chimie-2', 'bac-c-chimie-2-s1', 1),
('bac-c-chimie-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'bac-c-chimie-2', 'bac-c-chimie-2-s1', 2),
('bac-c-chimie-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'bac-c-chimie-2', 'bac-c-chimie-2-s1', 3),
('bac-c-chimie-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'bac-c-chimie-3', 'bac-c-chimie-3-s1', 1),
('bac-c-chimie-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'bac-c-chimie-3', 'bac-c-chimie-3-s1', 2),
('bac-c-svt-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'bac-c-svt-1', 'bac-c-svt-1-s1', 1),
('bac-c-svt-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'bac-c-svt-1', 'bac-c-svt-1-s1', 2),
('bac-c-svt-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'bac-c-svt-1', 'bac-c-svt-1-s1', 3),
('bac-c-svt-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'bac-c-svt-1', 'bac-c-svt-1-s1', 4),
('bac-c-svt-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'bac-c-svt-2', 'bac-c-svt-2-s1', 1),
('bac-c-svt-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'bac-c-svt-2', 'bac-c-svt-2-s1', 2),
('bac-c-svt-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'bac-c-svt-2', 'bac-c-svt-2-s1', 3),
('bac-c-svt-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'bac-c-svt-3', 'bac-c-svt-3-s1', 1),
('bac-c-svt-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'bac-c-svt-3', 'bac-c-svt-3-s1', 2),
('bac-d-mathematiques-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'bac-d-mathematiques-1', 'bac-d-mathematiques-1-s1', 1),
('bac-d-mathematiques-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'bac-d-mathematiques-1', 'bac-d-mathematiques-1-s1', 2),
('bac-d-mathematiques-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'bac-d-mathematiques-1', 'bac-d-mathematiques-1-s1', 3),
('bac-d-mathematiques-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'bac-d-mathematiques-1', 'bac-d-mathematiques-1-s1', 4),
('bac-d-mathematiques-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'bac-d-mathematiques-2', 'bac-d-mathematiques-2-s1', 1),
('bac-d-mathematiques-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'bac-d-mathematiques-2', 'bac-d-mathematiques-2-s1', 2),
('bac-d-mathematiques-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'bac-d-mathematiques-2', 'bac-d-mathematiques-2-s1', 3),
('bac-d-mathematiques-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'bac-d-mathematiques-3', 'bac-d-mathematiques-3-s1', 1),
('bac-d-mathematiques-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'bac-d-mathematiques-3', 'bac-d-mathematiques-3-s1', 2),
('bac-d-physique-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'bac-d-physique-1', 'bac-d-physique-1-s1', 1),
('bac-d-physique-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'bac-d-physique-1', 'bac-d-physique-1-s1', 2),
('bac-d-physique-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'bac-d-physique-1', 'bac-d-physique-1-s1', 3),
('bac-d-physique-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'bac-d-physique-1', 'bac-d-physique-1-s1', 4),
('bac-d-physique-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'bac-d-physique-2', 'bac-d-physique-2-s1', 1),
('bac-d-physique-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'bac-d-physique-2', 'bac-d-physique-2-s1', 2),
('bac-d-physique-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'bac-d-physique-2', 'bac-d-physique-2-s1', 3),
('bac-d-physique-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'bac-d-physique-3', 'bac-d-physique-3-s1', 1),
('bac-d-physique-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'bac-d-physique-3', 'bac-d-physique-3-s1', 2),
('bac-d-chimie-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'bac-d-chimie-1', 'bac-d-chimie-1-s1', 1),
('bac-d-chimie-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'bac-d-chimie-1', 'bac-d-chimie-1-s1', 2),
('bac-d-chimie-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'bac-d-chimie-1', 'bac-d-chimie-1-s1', 3),
('bac-d-chimie-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'bac-d-chimie-1', 'bac-d-chimie-1-s1', 4),
('bac-d-chimie-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'bac-d-chimie-2', 'bac-d-chimie-2-s1', 1),
('bac-d-chimie-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'bac-d-chimie-2', 'bac-d-chimie-2-s1', 2),
('bac-d-chimie-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'bac-d-chimie-2', 'bac-d-chimie-2-s1', 3),
('bac-d-chimie-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'bac-d-chimie-3', 'bac-d-chimie-3-s1', 1),
('bac-d-chimie-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'bac-d-chimie-3', 'bac-d-chimie-3-s1', 2),
('bac-d-svt-1-l1', 'Format et barème de l''épreuve', 'Comprendre la structure, la notation et les attentes.', 'bac-d-svt-1', 'bac-d-svt-1-s1', 1),
('bac-d-svt-1-l2', 'Gérer son temps le jour J', 'Répartir le temps entre les exercices efficacement.', 'bac-d-svt-1', 'bac-d-svt-1-s1', 2),
('bac-d-svt-1-l3', 'Rédaction et présentation', 'Rédiger clairement pour gagner tous ses points.', 'bac-d-svt-1', 'bac-d-svt-1-s1', 3),
('bac-d-svt-1-l4', 'Pièges fréquents à éviter', 'Les erreurs classiques qui coûtent des points.', 'bac-d-svt-1', 'bac-d-svt-1-s1', 4),
('bac-d-svt-2-l1', 'Sujet corrigé (session 1)', 'Résolution détaillée pas à pas d''un sujet d''examen.', 'bac-d-svt-2', 'bac-d-svt-2-s1', 1),
('bac-d-svt-2-l2', 'Sujet corrigé (session 2)', 'Résolution détaillée d''un autre sujet d''examen.', 'bac-d-svt-2', 'bac-d-svt-2-s1', 2),
('bac-d-svt-2-l3', 'Sujet corrigé (session 3)', 'Résolution détaillée d''un troisième sujet.', 'bac-d-svt-2', 'bac-d-svt-2-s1', 3),
('bac-d-svt-3-l1', 'Épreuve blanche 1', 'Composer en temps limité, puis se corriger.', 'bac-d-svt-3', 'bac-d-svt-3-s1', 1),
('bac-d-svt-3-l2', 'Épreuve blanche 2', 'Deuxième épreuve blanche chronométrée.', 'bac-d-svt-3', 'bac-d-svt-3-s1', 2)
) as v(slug,title,summary,chapter_slug,subchapter_slug,sort_order)
join chapters c on c.slug=v.chapter_slug
join subchapters sc on sc.slug=v.subchapter_slug
on conflict (slug) do nothing;

insert into activities (lesson_id, type, title, video_provider, sort_order)
select l.id, 'video', 'Vidéo (à venir)', 'placeholder', 0 from lessons l join chapters c on c.id=l.chapter_id
where c.slug in (
  'bac-c-chimie-1',
  'bac-c-chimie-2',
  'bac-c-chimie-3',
  'bac-c-mathematiques-1',
  'bac-c-mathematiques-2',
  'bac-c-mathematiques-3',
  'bac-c-physique-1',
  'bac-c-physique-2',
  'bac-c-physique-3',
  'bac-c-svt-1',
  'bac-c-svt-2',
  'bac-c-svt-3',
  'bac-d-chimie-1',
  'bac-d-chimie-2',
  'bac-d-chimie-3',
  'bac-d-mathematiques-1',
  'bac-d-mathematiques-2',
  'bac-d-mathematiques-3',
  'bac-d-physique-1',
  'bac-d-physique-2',
  'bac-d-physique-3',
  'bac-d-svt-1',
  'bac-d-svt-2',
  'bac-d-svt-3',
  'bepc-mathematiques-1',
  'bepc-mathematiques-2',
  'bepc-mathematiques-3',
  'bepc-spt-1',
  'bepc-spt-2',
  'bepc-spt-3',
  'bepc-svt-1',
  'bepc-svt-2',
  'bepc-svt-3',
  'cepd-mathematiques-1',
  'cepd-mathematiques-2',
  'cepd-mathematiques-3',
  'probatoire-c-chimie-1',
  'probatoire-c-chimie-2',
  'probatoire-c-chimie-3',
  'probatoire-c-mathematiques-1',
  'probatoire-c-mathematiques-2',
  'probatoire-c-mathematiques-3',
  'probatoire-c-physique-1',
  'probatoire-c-physique-2',
  'probatoire-c-physique-3',
  'probatoire-c-svt-1',
  'probatoire-c-svt-2',
  'probatoire-c-svt-3',
  'probatoire-d-chimie-1',
  'probatoire-d-chimie-2',
  'probatoire-d-chimie-3',
  'probatoire-d-mathematiques-1',
  'probatoire-d-mathematiques-2',
  'probatoire-d-mathematiques-3',
  'probatoire-d-physique-1',
  'probatoire-d-physique-2',
  'probatoire-d-physique-3',
  'probatoire-d-svt-1',
  'probatoire-d-svt-2',
  'probatoire-d-svt-3'
)
and not exists (select 1 from activities a where a.lesson_id=l.id and a.type='video');
